### ISSUE TITLE
Resistor tolerance strip should always be gold

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-dc#10]
For https://github.com/phetsims/tasks/issues/765.

The 4th strip switches between gold (±5%) and yellow (±4%), depending on the resistance
* 0-9 ohms: gold  
* 9.5-99 ohms: yellow 
* 99.5-100 ohms: gold 

Using the yellow strip for tolerance is problematic, because some half-steps (9.5, 10.5, 11.5 ohms) do not fall within the ±4% range. For example:
<img width="175" alt="screen shot 2017-01-18 at 1 30 15 pm" src="https://cloud.githubusercontent.com/assets/8419308/22081811/5a5ddcf0-dd82-11e6-9c3b-e34835fb349f.png">

Reading the strips on the resistor would indicate that the resistance is 10 ohms ±4%, or 9.60-10.40 ohms. If the tolerance strip was instead gold, the resistance would be 9.5-10.5 ohms.

@samreid I recommend that the 4th strip is always gold. This way we will avoid situations like the one in the example above. From a design perspective, I think it's also preferable to keep a consistent tolerance across all resistors.

An alternative would be to use a 5-strip resistor (which could accurately display all resistances), but that seems unnecessary to me.

**Comment by samreid** [comment]
Here is the current resistance to color algorithm, it looks like there are problems with decimal numbers and roundoffs, and possibly with the silver band:

```js
    getColorArray: function( resistance ) {

      // TODO: Rounding off values like 9.5 could be a problem.
      resistance = Math.round( resistance );

      if ( resistance < 10 ) {

        // Resistance is less than 10 Ohms
        return [ Color.black, digitToColor( resistance ), Color.black, gold ];
      }
      else if ( resistance < 100 ) {

        // The number is between 10 Ohms (inclusive) and 100 Ohms (exclusive)
        var tensPlaceDigit = Math.floor( resistance / 10 );
        var onesPlaceDigit = Math.floor( resistance % 10 );
        return [ digitToColor( tensPlaceDigit ), digitToColor( onesPlaceDigit ), Color.black, Color.yellow ];
      }
      else {
        var resistanceString = Util.toFixed( resistance, 0 );
        var firstDigit = parseInt( resistanceString.charAt( 0 ) + '', 10 );
        var secondDigit = parseInt( resistanceString.charAt( 1 ) + '', 10 );
        var factor = resistanceString.length - 2;

        var predicted = ( ( firstDigit * 10 + secondDigit ) * Math.pow( 10, factor ) );
        var error = ( resistance - predicted ) / predicted * 100;
        var tolerance = null;

        // A gold tolerance band is 5% tolerance, silver is 10%
        if ( error < 5 ) {
          tolerance = gold;
        }
        else if ( error < 20 ) {  // TODO: the note above says silver is 10% but this code looks like it is using 20%. WHY?
          tolerance = silver;
        }
        return [ digitToColor( firstDigit ), digitToColor( secondDigit ), digitToColor( factor ), tolerance ];
      }
    }
```

I was trying to dynamically compute the tolerance band.

@arouinfar can you please review this algorithm and see if you recommend any improvements?

**Comment by arouinfar** [comment]
@samreid looking at the first `else if` statement, it seems that the tolerance is manually set to `Color.yellow` when it returns:

`return [ digitToColor( tensPlaceDigit ), digitToColor( onesPlaceDigit ), Color.black, Color.yellow ];`

I'm not sure that I understand enough what's going on in the `else` statement to recommend further improvements, but I'd be happy to chat with you about it.

**Comment by samreid** [comment]
I'm thinking of rewriting the algorithm based on the description here:
https://en.wikipedia.org/wiki/Electronic_color_code

**Comment by samreid** [comment]
I have worked out a rough draft which is (a) not crashing and (b) appears to be a step in the right direction.  I'll commit it to master and I would like to add unit tests and think more about the tolerance band.

**Comment by samreid** [comment]
After some fine tuning, the new algorithm seems like it may be working OK.  However, we should discuss the tolerance bands.  For instance, for a 9.5 Ohm resistor, the implementation provides this color band scheme:

white,green,gold,gray

I cross checked this with https://www.allaboutcircuits.com/tools/resistor-color-code-calculator/ and saw the following:
![image](https://cloud.githubusercontent.com/assets/679486/25164504/96b89b06-248e-11e7-8f56-7a1e5b608114.png)

For many of the values we are modeling (0, 0.5, 1.0, 1.5, ......., 99.5, 100.0) we have a much better tolerance than 5%, and hence the algorithm is giving narrower tolerance bands.  However, I don't know if it is conventional to just use gold and silver or to use fine-grained tolerance bands according to the spec.  Also, I am somewhat concerned that if we use fine-grained tolerance bands (and they are always alternating colors as you adjust the resistance), it may be somewhat distracting.

**Comment by samreid** [comment]
Here are the computed tolerances for our supported resistors:

```
0.5 => 0.05
1.0 => 0.05
1.5 => 0.05
2.0 => 0.05
2.5 => 0.05
3.0 => 0.05
3.5 => 0.05
4.0 => 0.05
4.5 => 0.05
5.0 => 0.05
5.5 => 0.05
6.0 => 0.05
6.5 => 0.05
7.0 => 0.05
7.5 => 0.05
8.0 => 0.05
8.5 => 0.05
9.0 => 0.05
9.5 => 0.05
10.0 => 0.05
10.5 => 5.00
11.0 => 0.05
11.5 => 5.00
12.0 => 0.05
12.5 => 5.00
13.0 => 0.05
13.5 => 5.00
14.0 => 0.05
14.5 => 5.00
15.0 => 0.05
15.5 => 5.00
16.0 => 0.05
16.5 => 5.00
17.0 => 0.05
17.5 => 5.00
18.0 => 0.05
18.5 => 5.00
19.0 => 0.05
19.5 => 5.00
20.0 => 0.05
20.5 => 5.00
21.0 => 0.05
21.5 => 5.00
22.0 => 0.05
22.5 => 5.00
23.0 => 0.05
23.5 => 5.00
24.0 => 0.05
24.5 => 5.00
25.0 => 0.05
25.5 => 2.00
26.0 => 0.05
26.5 => 2.00
27.0 => 0.05
27.5 => 2.00
28.0 => 0.05
28.5 => 2.00
29.0 => 0.05
29.5 => 2.00
30.0 => 0.05
30.5 => 2.00
31.0 => 0.05
31.5 => 2.00
32.0 => 0.05
32.5 => 2.00
33.0 => 0.05
33.5 => 2.00
34.0 => 0.05
34.5 => 2.00
35.0 => 0.05
35.5 => 2.00
36.0 => 0.05
36.5 => 2.00
37.0 => 0.05
37.5 => 2.00
38.0 => 0.05
38.5 => 2.00
39.0 => 0.05
39.5 => 2.00
40.0 => 0.05
40.5 => 2.00
41.0 => 0.05
41.5 => 2.00
42.0 => 0.05
42.5 => 2.00
43.0 => 0.05
43.5 => 2.00
44.0 => 0.05
44.5 => 2.00
45.0 => 0.05
45.5 => 2.00
46.0 => 0.05
46.5 => 2.00
47.0 => 0.05
47.5 => 2.00
48.0 => 0.05
48.5 => 2.00
49.0 => 0.05
49.5 => 2.00
50.0 => 0.05
50.5 => 1.00
51.0 => 0.05
51.5 => 1.00
52.0 => 0.05
52.5 => 1.00
53.0 => 0.05
53.5 => 1.00
54.0 => 0.05
54.5 => 1.00
55.0 => 0.05
55.5 => 1.00
56.0 => 0.05
56.5 => 1.00
57.0 => 0.05
57.5 => 1.00
58.0 => 0.05
58.5 => 1.00
59.0 => 0.05
59.5 => 1.00
60.0 => 0.05
60.5 => 1.00
61.0 => 0.05
61.5 => 1.00
62.0 => 0.05
62.5 => 1.00
63.0 => 0.05
63.5 => 1.00
64.0 => 0.05
64.5 => 1.00
65.0 => 0.05
65.5 => 1.00
66.0 => 0.05
66.5 => 1.00
67.0 => 0.05
67.5 => 1.00
68.0 => 0.05
68.5 => 1.00
69.0 => 0.05
69.5 => 1.00
70.0 => 0.05
70.5 => 1.00
71.0 => 0.05
71.5 => 1.00
72.0 => 0.05
72.5 => 1.00
73.0 => 0.05
73.5 => 1.00
74.0 => 0.05
74.5 => 1.00
75.0 => 0.05
75.5 => 1.00
76.0 => 0.05
76.5 => 1.00
77.0 => 0.05
77.5 => 1.00
78.0 => 0.05
78.5 => 1.00
79.0 => 0.05
79.5 => 1.00
80.0 => 0.05
80.5 => 1.00
81.0 => 0.05
81.5 => 1.00
82.0 => 0.05
82.5 => 1.00
83.0 => 0.05
83.5 => 1.00
84.0 => 0.05
84.5 => 1.00
85.0 => 0.05
85.5 => 1.00
86.0 => 0.05
86.5 => 1.00
87.0 => 0.05
87.5 => 1.00
88.0 => 0.05
88.5 => 1.00
89.0 => 0.05
89.5 => 1.00
90.0 => 0.05
90.5 => 1.00
91.0 => 0.05
91.5 => 1.00
92.0 => 0.05
92.5 => 1.00
93.0 => 0.05
93.5 => 1.00
94.0 => 0.05
94.5 => 1.00
95.0 => 0.05
95.5 => 1.00
96.0 => 0.05
96.5 => 1.00
97.0 => 0.05
97.5 => 1.00
98.0 => 0.05
98.5 => 1.00
99.0 => 0.05
99.5 => 1.00
100.0 => 0.05
```

It looks like the max tolerance is 5% (gold) which occurs 10.5-24.5 ohms.  @arouinfar do you recommend going with narrow, specific tolerances that vary or a fixed, less specific tolerance that remains constant?

**Comment by samreid** [comment]
I noticed in the original comment @arouinfar said:

> From a design perspective, I think it's also preferable to keep a consistent tolerance across all resistors.

I'll go for that.

**Comment by samreid** [comment]
In the above commit, I eliminated tolerances less than gold, but left silver in case we ever need it (though it doesn't appear in our 0.5-100 ohm range).  

I also noticed that the specification color of gold from the wikipedia page doesn't show up too well against our resistor color:

![image](https://cloud.githubusercontent.com/assets/679486/25164941/ff3ae808-2490-11e7-92e7-e31f97c6942d.png)

I'm somewhat interested in using the colors from the specification (in the new implementation), @arouinfar how do you feel about updating the resistor image color so it is easier to see gold and the other shades?

**Comment by arouinfar** [comment]
@samreid I pulled the gold color from your screenshot and tweaked the color of the resistor. In Illustrator the resistor has a transparent white shape layered over a darker coppery color. Originally, the white layer's opacity was set to 50%, but I've reduced it further to 30%, which seems to do the trick.

Here's a comparison of the updated (top) and original (bottom) resistors
![image](https://cloud.githubusercontent.com/assets/8419308/25201969/d858930e-2510-11e7-9a3b-2f15f78878e5.png)

@samreid if you're happy with the color, I can send you an updated asset.

**Comment by samreid** [comment]
That looks a lot better to me, but at the small size it appears in the sim, it is still difficult to distinguish the gold bar.  Can you adjust further or recommend a different shade of gold?

**Comment by arouinfar** [comment]
Thanks for the feedback @samreid. I've tweaked the gold color a bit (#e6b600), and darkened the resistor. I think this looks pretty good: 
<img width="340" alt="screen shot 2017-04-20 at 10 38 24 am" src="https://cloud.githubusercontent.com/assets/8419308/25242077/a1a346b0-25b5-11e7-8625-3c9893ec6c2b.png">

**Comment by samreid** [comment]
Those colors look great, I'll add the gold.  Can you provide the new image?

**Comment by arouinfar** [comment]
Sent! Back to you @samreid.

**Comment by samreid** [comment]
Updated, here it is in context: 
![image](https://cloud.githubusercontent.com/assets/679486/25244352/9810c4ee-25bd-11e7-8589-9485fb75baa5.png)

Brown (in the default 10 ohm resistor) kind of blends in--what do you think?

**Comment by arouinfar** [comment]
Aaah, good catch @samreid. Perhaps I should make the resistor a bit lighter, then.

**Comment by arouinfar** [comment]
@samreid I've dialed the resistor darkness back a bit. I'll email you the updated assets.
![image](https://cloud.githubusercontent.com/assets/8419308/25597312/4277f06c-2e8b-11e7-899e-1337d5d80f79.png)

**Comment by samreid** [comment]
Committed above and looks great in the app.

**Comment by samreid** [comment]
@arouinfar please review and close if all is well:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.14/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
👍
