### ISSUE TITLE
Be able to "click through" the voltage probe wires

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-dc#103]
In version dev.91, it seems that the voltage probe wires block clicking so when they go over the battery or other elements, it makes it more difficult to grab or highlight those elements for changing values, moving, or deleting. It would be good to make these wires essentially "see through" as far as the mouse is concerned.

**Comment by samreid** [comment]
Thanks for reporting this issue, @kathy-phet.  In the preceding commit I made the voltmeter and ammeter wires unpickable.  Here's a dev version with the fix:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.99/circuit-construction-kit-dc_en.html

@kathy-phet or @arouinfar can you please verify?  Be aware that dev.99 is many commits beyond dev.91 so cannot be used as a "safe sha" maintenance release.

**Comment by kathy-phet** [comment]
Thx Sam, I will use 91.

Sent from my iPhone

On Jul 23, 2017, at 3:23 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #103<https://github.com/phetsims/circuit-construction-kit-dc/issues/103> to @kathy-phet<https://github.com/kathy-phet>.

**Comment by arouinfar** [comment]
Looks good to me @samreid!
