### ISSUE TITLE
Diameter of electron representation?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-dc#104]
@arouinfar I noticed this while thinking about https://github.com/phetsims/circuit-construction-kit-dc/issues/77

Should we consider some changes to the electron representation diameter? I think if the electrons were smaller things with the lightbulb would be a bit easier.

My more pressing concern is that in the Java sim, the electrons are contained fully within the wire (the wires are thicker in comparison to other elements). I like the size of the current wire but perhaps we should consider matching the electron diameter to the width of the wire? I feel like some confusion could occur as to "why do the electrons protrude slightly from the wire, but no other circuit element"

@samreid I imagine this is a quick change to try in master?

**Comment by samreid** [comment]
I tried cutting the size in half as a first guess, it looks like a good fit to the wire, but perhaps more difficult to tell it is an electron?

![image](https://user-images.githubusercontent.com/679486/28547081-797867fe-708a-11e7-83f9-3dc96b6a74f3.png)

0.75 seems much better:
![image](https://user-images.githubusercontent.com/679486/28547114-9f909006-708a-11e7-9c41-1472a9598bae.png)

it looks like the electron isn't exactly centered either--perhaps I'll need to make an adjustment there as well.

**Comment by samreid** [comment]
I subtracted 1/2 from the positions and it seemed to help:
![image](https://user-images.githubusercontent.com/679486/28547198-0a6cc48a-708b-11e7-9054-3586f8ecd670.png)

**Comment by samreid** [comment]
Here's a live version with 0.75, please test:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.101/circuit-construction-kit-dc_en.html

**Comment by ariel-phet** [comment]
I definitely prefer this smaller size, and it seems to work nicely in the sim and be more consistent with the conventional current arrows (which fit inside all elements.

What do you think @arouinfar? I might even consider keeping the diameter at 0.75 and bumping up the wire radius ever so slightly to match.

**Comment by arouinfar** [comment]
> I feel like some confusion could occur as to "why do the electrons protrude slightly from the wire, but no other circuit element"

Excellent point @ariel-phet. I didn't notice anything in interviews, but I could see it being an issue for some (particularly younger) students.

@samreid thanks for adjusting the electron size. I think dev.101 looks really clean. I don't find that the electrons get "in the way" as much, either. I would like to see the wire radius bumped up slightly as @ariel-phet suggested.

**Comment by samreid** [comment]
Current width is 12 and looks like this:

![image](https://user-images.githubusercontent.com/679486/28547853-1a48b668-708e-11e7-8a16-96619e2c82a3.png)

Here is 14:

![image](https://user-images.githubusercontent.com/679486/28547864-26b429d2-708e-11e7-846f-40a967c87c84.png)

Here is 15:
![image](https://user-images.githubusercontent.com/679486/28547944-8a27f610-708e-11e7-9260-90f91c757534.png)

Here is 16:
![image](https://user-images.githubusercontent.com/679486/28547876-35e3096e-708e-11e7-8c4c-73831019d0f3.png)

Place your votes!

**Comment by arouinfar** [comment]
@samreid I vote for the thinnest wire that can still fully enclose the electrons, which looks to be 14 (hard to tell in the screenshot), but if not I'd go with 15.

**Comment by samreid** [comment]
Upon reflection, I'm hoping to keep the wire width an even number since it is halved for creating rasters.  14 width and 0.75 electron size leaks off the edge a little bit.  So my choices for the wire are 14 or 16, and I can tweak the electron size a little bit to compensate.

**Comment by samreid** [comment]
At 14 wire width, 0.68 electron size kept most of it in the wire, but that seemed a bit small.  I'll try 16.

**Comment by samreid** [comment]
16 and 0.78 looks pretty good, committing.

**Comment by samreid** [comment]
Dev version with 16 and 0.78 is here, @arouinfar and @ariel-phet can you take a look?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.102/circuit-construction-kit-dc_en.html

**Comment by ariel-phet** [comment]
@samreid that looks really nice to my eye. The only issue I see is that the wire in the carousel has funky ends (perhaps the icon did not get the end caps altered?)

![capture](https://user-images.githubusercontent.com/4051174/28550050-9fd808f8-709b-11e7-9401-f6bac0a3f1fa.PNG)

**Comment by phet-steele** [comment]
> @samreid that looks really nice to my eye. The only issue I see is that the wire in the carousel has funky ends (perhaps the icon did not get the end caps altered?)

@ariel-phet If I may refer you to https://github.com/phetsims/circuit-construction-kit-common/issues/390

**Comment by samreid** [comment]
Sounds good, I'll close this one and we can continue in the issue @phet-steele pointed out.
