### ISSUE TITLE
Carousels should be the same size on each screen

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#105]
In #91 @arouinfar said:

Switching between the screens, it looks like the Lab carousel is just a tad taller than the Intro carousel, though.

**Comment by samreid** [comment]
Proposed fix is in this new dev version:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.109/circuit-construction-kit-dc_en.html

@arouinfar can you please check it out?

**Comment by arouinfar** [comment]
Looks good. Thanks @samreid!
