### ISSUE TITLE
Decide on the layering of the "east" socket electron

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#106]
In https://github.com/phetsims/circuit-construction-kit-dc/issues/77 charges got a dedicated layer instead of changing layer order.  This changed the behavior from (dev.91)

![image](https://user-images.githubusercontent.com/679486/28627596-8227af44-71df-11e7-8e52-1823efdcbcf1.png)

to (dev.107)

![image](https://user-images.githubusercontent.com/679486/28627652-ae91a616-71df-11e7-9949-3d943abf2f61.png)

Note how the east electron is in front on dev.91 and behind on dev.107.

@arouinfar said:

> The electrons in dev.107 have a bit of a strange transition from the right vertex to the filament, but I don't find it to be problematic. If we decide to go with dev.107, I don't think we need to create special-case layering for the right vs. bottom of the socket as @samreid.

I provided time and complexity estimates in #77.  But I'm currently in agreement with @arouinfar that the dev.107 behavior is acceptable--this issue is to make sure @ariel-phet and @kathy-phet are aware of this difference and to determine if it is OK as is or if we need to get back to the dev.91 behavior.

**Comment by samreid** [comment]
Java has the east electron on top:
![image](https://user-images.githubusercontent.com/679486/28628639-72041e42-71e2-11e7-9689-98815bc39f40.png)

And the filament wire is on top too:
![image](https://user-images.githubusercontent.com/679486/28628660-7d978fbe-71e2-11e7-91fe-47d0888f3966.png)

I don't think it's essential to match the Java version, but I wanted to provide these screenshots in our discussion.

**Comment by ariel-phet** [comment]
I am fine with the behavior in dev.107 

I feel like this behavior keeps the impression of moving along the filament and still "under" the lightbulb glass.

**Comment by kathy-phet** [comment]
Looks fine to me too.

Sent from my iPhone

On Jul 26, 2017, at 12:17 PM, Ariel Paul <notifications@github.com<mailto:notifications@github.com>> wrote:


I am fine with the behavior in dev.107

I feel like this behavior keeps the impression of moving along the filament and still "under" the lightbulb glass.

**Comment by samreid** [comment]
Sounds good, thanks, closing.
