### ISSUE TITLE
Memory testing

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#116]
fuzz testing is showing a leak now, we should investigate before code review or dev testing.

**Comment by samreid** [comment]
My test routine:
update Sim.js with this code:

```js
      // fire or synthesize input events
      if ( phet.chipper.queryParameters.fuzzMouse && this.frameCounter > 60 * 5 && this.frameCounter < 60 * 10 ) {
        this.display.fuzzMouseEvents( phet.chipper.queryParameters.fuzzRate );
      }
```

Launch the sim with ?fuzzMouse.

Take an initial memory snapshot.

Let it fuzz for 5 seconds.

Press reset on each screen

Take a memory snapshot and compare.

We may need some "warm up fuzzing" before this starts?

**Comment by samreid** [comment]
New routine:

```js

      var isFuzzTime = this.frameCounter < 60 * 5 || (this.frameCounter > 60 * 10 && this.frameCounter < 60 * 15);

      // fire or synthesize input events
      if ( phet.chipper.queryParameters.fuzzMouse && isFuzzTime ) {
        this.display.fuzzMouseEvents( phet.chipper.queryParameters.fuzzRate );
      }
```
launch with ?fuzzMouse
let it fuzz 5 sec (warming up phase)
reset both screens and capture a memory snapshot
let it fuzz 5 sec (testing phase)
reset both screens and capture a memory snapshot
compare memory snapshots

**Comment by samreid** [comment]
After @jonathanolson & I addressed many leaks, we are still seeing about 1MB leaked per 10 seconds with fuzzMouse (and resets).  Here's a pic of what is still leaking:

![image](https://user-images.githubusercontent.com/679486/28705972-5e9fbb24-732f-11e7-8b47-c93255c7f763.png)

**Comment by samreid** [comment]
One leak is that ResistorNode continually creates new rasters during startup for each of the different resistor types.

**Comment by samreid** [comment]
Same deal for CircuitConstructionKitLightBulbNode

**Comment by samreid** [comment]
Fuzz on and off every 10 seconds

```js
      var tensOfSeconds = Math.round( this.frameCounter / 60 / 10 );
      // console.log( tensOfSeconds );
      var isFuzzTime = tensOfSeconds % 2 === 1;

      // fire or synthesize input events
      if ( phet.chipper.queryParameters.fuzzMouse && isFuzzTime ) {
        this.display.fuzzMouseEvents( phet.chipper.queryParameters.fuzzRate );
      }
```

**Comment by samreid** [comment]
After fixing the above errors, I ran the following test:

grunt --mangle=false
?fuzzMouse&fuzzRate=3000

snapshot times
1: 7:29am  54.6MB
2: 7:32am  52.2MB
3: 7:46am  65.4MB
4: 7:49am  76.1MB
5: 7:53am  55.4MB
6: 7:57am  66.9MB
7: 8:07am  79.9MB
8: 8:09am  75.9MB
9: 8:41am  74.3MB

![image](https://user-images.githubusercontent.com/679486/28722391-d4e9de2c-7370-11e7-80ee-d4d2c494d62e.png)

It looks like memory usage stabilized somewhere around 30 minutes.

![image](https://user-images.githubusercontent.com/679486/28722536-561ea2a2-7371-11e7-8b2f-26472d40d301.png)

It seems there are no memory leaks, closing.

**Comment by samreid** [comment]
2:24pm 34MB

**Comment by samreid** [comment]
http://localhost/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?brand=phet&ea&fuzzMouse
10:28am: 64.9MB
10:34am: 62.4MB

**Comment by samreid** [comment]
Built version:

12:15pm 49.5MB
12:17pm 54.7MB
12:20pm 64.8MB
12:23pm 67.2MB
12:25pm 72.0MB
12:30pm 73.6MB
12:35pm 83.4MB

**Comment by jonathanolson** [comment]
I was testing a built version (and turning off fuzzing and doing reset-all on both screens) and it seemed stable after about an hour, generally between 46MB and 52MB (slight variation each time).
