### ISSUE TITLE
Highlight region truncated for high resistance bulb on iPad2

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#117]
![image](https://user-images.githubusercontent.com/679486/28723961-b10135e6-7375-11e7-9c86-091f552d5a6d.png)

**Comment by samreid** [comment]
I haven't been able to reproduce this problem.  @phet-steele can you keep your eyes peeled for this sort of this in the next round of testing?

**Comment by phet-steele** [comment]
@samreid, if a component (any) starts its life in schematic view, then its highlight will fit the size of the schematic, not the normal size. So, switch to schematic view, then drag out a light bulb (don't care which type). Then switch to normal view and drag out another lightbulb. Then you can compare their sizes. Not specific to platform either, I believe.

**Comment by samreid** [comment]
If I initialize the highlight regions based on the lifelike view, then the schematic view looks like this:

![image](https://user-images.githubusercontent.com/679486/28783429-92d20a14-75cd-11e7-95a3-075dd67e8de2.png)

@arouinfar is that acceptable?  Or should the highlight regions be recomputed when changing between lifelike and schematic?

**Comment by samreid** [comment]
Proposed fix committed above, @arouinfar can you please double check everything?

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.121/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Updated highlight looks good! Thanks @samreid.
