### ISSUE TITLE
Animation speed text overlaps radio buttons

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#118]
![image](https://user-images.githubusercontent.com/679486/28725617-42be7d68-737b-11e7-836c-3645452ec481.png)

**Comment by samreid** [comment]
It depends on the aspect ratio--can be worse and changing the y position isn't necessarily the best solution:

![image](https://user-images.githubusercontent.com/679486/28726483-a89c77a4-737e-11e7-8194-0b1e84c2ec26.png)

**Comment by samreid** [comment]
The new version looks like this:
![image](https://user-images.githubusercontent.com/679486/28730000-b76b9848-738b-11e7-92d4-05587ffd6f85.png)

@arouinfar can you please review?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.115/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Looks much better now! Thanks @samreid
