### ISSUE TITLE
Circuit elements should pop up above touch events

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#119]
On iPad2, the finger obscures the circuit element when dragged out of the toolbox.  It would be better to pop it up some pixels or grab it near the bottom so it is easier to see.  Not sure if this should be same "grab point" for touch and mouse, or if touch should be a special case.  @arouinfar what do you think?

**Comment by arouinfar** [comment]
@samreid it looks like the "grab point" is currently the middle of the object. I think you could move it down to the bottom and that would alleviate the issue on iPad. I would use the same grab point for touch and mouse -- no need to create a special case.

**Comment by samreid** [comment]
My gut reaction on seeing a wire drag out by the bottom center (by the mouse) is that it feels buggy--I'm sure this is to some extent because I'm used to the center drag. But it makes me wonder how complex it would be to separate these--if it is just a few lines of code, we should maybe go for it.

**Comment by arouinfar** [comment]
> if it is just a few lines of code, we should maybe go for it.

Sounds good @samreid

**Comment by samreid** [comment]
Proposed fix is here.  @arouinfar can you please test? 
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.116/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
@samreid did you end up going the touch-only route? Things look the same on my Mac.

**Comment by samreid** [comment]
Yes, the modified vertical translation is for touch only, the behavior for dragging should still be the same (except the centering was fixed for the light bulb.)

**Comment by samreid** [comment]
By the way, on Mac Chrome you can open the console and click the 2nd icon (that looks like a phone next to an iPad).

![image](https://user-images.githubusercontent.com/679486/28754231-beb26932-74fe-11e7-871d-92dcac09d7b5.png)

That will let you choose a device profile:
![image](https://user-images.githubusercontent.com/679486/28754237-ce3f938e-74fe-11e7-945b-4fc76fac4694.png)

and then you can simulate touch events using the mouse.  This should not replace on-device testing, but may come in handy sometimes.

**Comment by arouinfar** [comment]
Thanks for the tip @samreid! Tested the latest dev on iPad, and the popping elements look really nice.
