### ISSUE TITLE
Light Bulb icons look crummy on Edge

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#120]
![image](https://user-images.githubusercontent.com/679486/28732389-88fbaf1a-738c-11e7-81fd-5610570a4d31.png)

**Comment by samreid** [comment]
Discovered in https://github.com/phetsims/circuit-construction-kit-dc/issues/109

**Comment by samreid** [comment]
Mipmaps solved this same problem for firefox, but not on edge.

**Comment by samreid** [comment]
dev.117 tried to fix the navbar icon.  it is better but still pretty bad (depends on exact screen size)

![image](https://user-images.githubusercontent.com/679486/28733745-69b45caa-7392-11e7-8c8a-cd7dc29223bf.png)

**Comment by samreid** [comment]
@jonathanolson what do you recommend here?

**Comment by jonathanolson** [comment]
Is that on a retina screen? I'm curious if it's not properly adjusting mipmaps (or is over-adjusting mipmaps) on Edge, and maybe a mipmap level adjustment would help.

**Comment by samreid** [comment]
It is a nonretina screen, how do I do a level adjustment?

**Comment by jonathanolson** [comment]
If it's WebGL, I'd need to look it up.

If it's SVG/Canvas, adjust the Image node's mipmapBias (see setMipmapBias docs, note default is currently -0.7).

**Comment by samreid** [comment]
Those are SVG, I'll give that a try

**Comment by jonathanolson** [comment]
Forgot that Edge forces default to Canvas (because of SVG rendering issues).

I tried (?) changing the mipmapBias a lot and I saw no change (so I'm going to wait to investigate at home to debug further)

**Comment by samreid** [comment]
I tried removing the "edge is only canvas" logic and everything looked beautiful.

![image](https://user-images.githubusercontent.com/679486/28738832-c1b2a3c2-73aa-11e7-9744-a8c3eb194c01.png)

The ellipses were even OK.  Should we look into removing that workaround now?  My edge is 40.15063.0.0

**Comment by phet-steele** [comment]
@samreid, maybe try the three test links at the top of this issue: https://github.com/phetsims/scenery/issues/515

**Comment by jonathanolson** [comment]
I see comments in https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3723601/ that indicate some text issues may be fixed in "EdgeHTML 15 / Edge 40" which should be in the Win10 "creators" update.

I'd recommend some investigation to see if we can identify Edge versions where our canvas workarounds aren't needed, so that we don't introduce other problems (like this).

I'll look into testing on latest Edge, and our browser usage on the website.

**Comment by jonathanolson** [comment]
Looks like Edge 14.x is somewhat more common than Edge 15.x (with 13.x and 12.x trailing off quickly).

**Comment by samreid** [comment]
Cursory testing on edge 14 with svg looks legit

![image](https://user-images.githubusercontent.com/679486/28786466-8b4b9cb6-75d6-11e7-8c8c-a6b8623bef91.png)

Though I did see one occurrence of an ellipsis about 20px to the left.

**Comment by samreid** [comment]
@jonathanolson determined that mipmaps are not used on canvas.  We'll investigate adding that feature and it may address this problem (leaving renderer as canvas on Edge).

**Comment by samreid** [comment]
The scenery change looks great, here's the before/after:

![image](https://user-images.githubusercontent.com/679486/28793582-a7b5fc56-75f0-11e7-996f-f9b89d453ce1.png)
