### ISSUE TITLE
Issues with the battery value display

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#121]
The battery value display is left-justified, which means the 8 lines up with the 7 in this example:

![image](https://user-images.githubusercontent.com/679486/28732567-21194258-738d-11e7-8571-c487758fdd17.png)

This could be confusing or easily misread.  It may be better to:
1. Right justify
2. Align the decimal points
3. Drop the decimal point for the battery resistance (because it can only be set to integers anyways)
4. 2 and 3 (except align the ones place because there would be no decimal)
5. leave it as it is

5 would be easiest, with 1 coming in 2nd place.  All other solutions are a bit more complicated, but nothing over 2 hours.

@arouinfar what do you recommend?

**Comment by arouinfar** [comment]
@samreid I'm not sure how left-aligning the battery values would be confusing. I didn't witness any student difficulty in interpreting the values during interviews, so I'm inclined to go with option (5) and leave things as they are.

**Comment by samreid** [comment]
I don't recall which sim, but in a recent (<1 yr) sim design, we decided it was important to line up the decimal points to make sure the orders of magnitude weren't confusing and the numbers could be easily compared.  It may be less concerning in this simulation if the ohms and volts values aren't compared often.  However, it does seem like it would be aesthetically pleasing to line up the V and Ohm symbols though.  So I briefly tried changing "left align" to "right align" and it came out like this:

![image](https://user-images.githubusercontent.com/679486/28762804-9e66911c-7576-11e7-9089-33052ed284d7.png)

Now it is kind of bothersome that the decimal points aren't lined up too well (because of the size mismatch between V and ohm character).  But on the other hand, it is nice how the symbols are lined up and the orders of magnitude can be easily judged.

I understand that there was no confusion during interviews but wanted to discuss a bit further since this will be easier to change now than later (if we ever decide to change it).  I guess one of my questions is: what is wrong with right justification (aside from the decimals not being lined up exactly)?

**Comment by samreid** [comment]
Also, how come the top post has borders around the numbers and the snapshot above does not?

**Comment by arouinfar** [comment]
Thanks for the clarification @samreid. Now that I see the right-aligned values, I prefer that arrangement, as it makes it a bit clearer which number is larger/has more digits. I am not bothered by the slightly misaligned decimal points, however. I think aligning the decimals would introduce a strange staggering of the units, which I would find more distracting.

I change my vote to right-aligning the battery values.

**Comment by samreid** [comment]
Right alignment is ready in this version, @arouinfar can you please test?

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.126/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
👍
