### ISSUE TITLE
Layout bounds are incorrect UNTIL I zoom

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#123]
From https://github.com/phetsims/circuit-construction-kit-dc/issues/99

@phet-steele said:

Ack, @samreid I don't know if this is new or not, but now layout bounds are incorrect UNTIL I zoom. So right from sim opening, I drag out a sensor and am not allowed to drag out of dev bounds. Once I zoom out then in, everything is fine. Just tried this on master.

**Comment by samreid** [comment]
@phet-steele I published a proposed solution here, can you please test?

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.125/circuit-construction-kit-dc_en.html

**Comment by phet-steele** [comment]
Bounds are looking correct at all times for me. 😄
