### ISSUE TITLE
Sometimes the wire body doesn't appear in the toolbox

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#124]
I've seen this twice now. Last sighting was in requirejs (not sure where 1st sighting was).

This is Mac/Chrome on current master:

![image](https://user-images.githubusercontent.com/679486/28792268-467154b2-75ec-11e7-84ed-0ef9018480c6.png)

@jonathanolson any guesses what might be happening here?

**Comment by jonathanolson** [comment]
Might be related to image loading.

Will want to inspect a case where this has happened, or have reproduction instructions (can't reproduce locally).

**Comment by samreid** [comment]
I refreshed 15 times and haven't seen it again yet.

**Comment by samreid** [comment]
I published http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.129/circuit-construction-kit-dc_en.html with an icon loaded through image!

**Comment by samreid** [comment]
@phet-steele tested it out and we decided we like this fix.  Closing.

**Comment by phet-steele** [comment]
@samreid, looked again and the fix doesn't handle switching to schematic view. The non-schematic wire is always shown in the carousel.

**Comment by samreid** [comment]
I committed the proposed fix, @phet-steele can you please verify?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.130/circuit-construction-kit-dc_en.html

**Comment by phet-steele** [comment]
Second time's the charm! (right?)
