### ISSUE TITLE
What happened to negative voltage readings?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#128]
Either way I put this voltmeter, it always shows positive:

<img width="549" alt="screen shot 2017-08-03 at 1 32 42 pm" src="https://user-images.githubusercontent.com/5863899/28939960-46996338-7850-11e7-8f7f-7a357b07ac0c.png">
<img width="626" alt="screen shot 2017-08-03 at 1 32 48 pm" src="https://user-images.githubusercontent.com/5863899/28939961-46adc2b0-7850-11e7-997e-b22b3d586e7c.png">

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/33.
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.135/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.135 2017-08-02 19:46:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
Language: en-US
Window: 1920x1012
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"0e3d5567","branch":"master"},"babel":{"sha":"51a4bd3b","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"6829432d","branch":"master"},"circuit-construction-kit-common":{"sha":"ee9efcbe","branch":"master"},"circuit-construction-kit-dc":{"sha":"5e5b0c9f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"8a235835","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"phet-core":{"sha":"d8bec6c1","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"9f5612d2","branch":"master"},"scenery-phet":{"sha":"23839a28","branch":"master"},"sherpa":{"sha":"be8e800b","branch":"master"},"sun":{"sha":"a56ba571","branch":"master"},"tandem":{"sha":"29cd4f63","branch":"master"},"twixt":{"sha":"3ca102d0","branch":"master"}}

**Comment by samreid** [comment]
Thanks @phet-steele, I've published a proposed fix here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.136/circuit-construction-kit-dc_en.html

**Comment by phet-steele** [comment]
Voila!
