### ISSUE TITLE
Investigate strobing

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#129]
@kathy-phet reported a strobe effect on her CPU-burdened laptop where the electrons appeared to move backwards.  @phet-steele can you test this?

**Comment by samreid** [comment]
@kathy-phet suggested I could build a version with dynamic dt for her to compare.

**Comment by phet-steele** [comment]
@kathy-phet @samreid I certainly need more info (or even a video/screenshot). Things like, was the circuit being dragged? What was the current? etc...

**Comment by phet-steele** [comment]
@kathy-phet showed me in person. Simple battery + lightbulb with high current (and long wires), coupled with taxing the system, makes it happen for her.

**Comment by samreid** [comment]
I changed 

```js
var maxPositionChange = maxSpeed * MAX_DT; // Use the max dt instead of the true dt to avoid fluctuations
```

to
```js
var maxPositionChange = maxSpeed * dt;
```

which I thought would make it dynamic based on `dt` and still prevent strobing, but I saw electrons start to go backwards when the current was too high.

**Comment by samreid** [comment]
It is difficult for me to reproduce this problem in Mac/Chrome and `makeEverythingSlow` doesn't seem to help.

**Comment by kathy-phet** [comment]
@samreid - Can you publish a comparative dev version so I can see the A-B between the dt behavior in v28 and the dt behavior now? I saw some other behavior differences, and I want to see if it is tied to that code. Thx.

**Comment by samreid** [comment]
This version (not committed) uses `maxSpeed * dt`:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.138/circuit-construction-kit-dc_en.html

**Comment by kathy-phet** [comment]
They both show strobing. 
Kathy

**Comment by samreid** [comment]
I'm unable to see strobing on dev.137 on my Mac or iPad2, even when I try to hinder performance.  @phet-steele can you replicate this problem so we can investigate further?

**Comment by samreid** [comment]
Is this issue superceded by https://github.com/phetsims/circuit-construction-kit-dc/issues/164 ?

**Comment by phet-steele** [comment]
@samreid I was just going to ask you!

**Comment by samreid** [comment]
@ariel-phet what do you think?

**Comment by ariel-phet** [comment]
Yes, this seems like a duplicate of #164, closing as such
