### ISSUE TITLE
The sim should have 3 screens

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#13]
Split into screens -- probably an “intro” and “lab” -- to be named

Intro screen would have pared-down option set.

Teachers should be able to use a query parameter with just one screen.

On the sim page we could add an “options” section that would launch the sim using different query parameters

One possibility is for the “lab” screen to have only real-world components (no non-contact ammeter, for example). 

@arouinfar said she would mock up the screens.

**Comment by arouinfar** [comment]
@samreid preliminary mockups of both screens are in the design doc. I've also added a discussion of Intro vs. Lab to the to the table for the next design meeting. I'm going to go ahead and close this issue.

**Comment by samreid** [comment]
Should I leave this issue open until the 2nd screen is added in the code?

**Comment by arouinfar** [comment]
It's up to you @samreid, but I think it makes more sense for you to be the one assigned.

**Comment by samreid** [comment]
I've added the screens, we can fill them out in other issues, closing.
