### ISSUE TITLE
Uncaught TypeError: Cannot read property 'globalToParentPoint' of undefined

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#130]
@samreid this is a multitouch bug that involves a touchscreen, OR can be done with a mouse and keyboard (using the snazzy delete/backspace button functionality).

If touch:
1. While dragging a VERTEX (not the body of a component), press the Reset All button with another finger.

If mouse & keyboard:
1. Connect two components.
2. Click on the connection to bring up the scissors (don't click the button!).
3. Start dragging the same connection around with your mouse.
4. While dragging, and while the cut button is still active, press delete/backspace on your keyboard.

This quite drastically make the sim unusable. You can't interact with anything using a mouse, and touch capability becomes limited. Both cases fail with this assertion:
```
Uncaught TypeError: Cannot read property 'globalToParentPoint' of undefined
    at CircuitLayerNode.dragVertex (CircuitLayerNode.js?bust=1502213867501:528)
    at drag (VertexNode.js?bust=1502213867501:191)
    at Object.move (SimpleDragHandler.js?bust=1502213867501:131)
    at Input.dispatchToListeners (Input.js?bust=1502213867501:790)
    at Input.dispatchEvent (Input.js?bust=1502213867501:760)
    at Input.branchChangeEvents (Input.js?bust=1502213867501:688)
    at Input.moveEvent (Input.js?bust=1502213867501:653)
    at Input.mouseMove (Input.js?bust=1502213867501:353)
    at Input.pointerMove (Input.js?bust=1502213867501:595)
    at BatchedDOMEvent.run (BatchedDOMEvent.js?bust=1502213867501:57)
```

Seen on macOS 10.12.6 Chrome and iPad Air 2 iOS 10.3.2. For phetsims/QA/issues/33.

URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.135/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.135 2017-08-02 19:46:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
Language: en-US
Window: 1920x1012
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"0e3d5567","branch":"master"},"babel":{"sha":"51a4bd3b","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"6829432d","branch":"master"},"circuit-construction-kit-common":{"sha":"ee9efcbe","branch":"master"},"circuit-construction-kit-dc":{"sha":"5e5b0c9f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"8a235835","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"phet-core":{"sha":"d8bec6c1","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"9f5612d2","branch":"master"},"scenery-phet":{"sha":"23839a28","branch":"master"},"sherpa":{"sha":"be8e800b","branch":"master"},"sun":{"sha":"a56ba571","branch":"master"},"tandem":{"sha":"29cd4f63","branch":"master"},"twixt":{"sha":"3ca102d0","branch":"master"}}

**Comment by samreid** [comment]
Thanks @phet-steele, the proposed fix is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.140/circuit-construction-kit-dc_en.html

Can you please test it out?

**Comment by phet-steele** [comment]
Fixed.
