### ISSUE TITLE
Switch highlight is dynamic and can obscure the switch

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#132]
@samreid, the size of the switch's highlight is dependent on its open/closed state when switching between schematic/normal view.

1. In normal view, drag out an open switch.
2. Click it, the highlight box is of the "bigger" variant.

<img width="335" alt="screen shot 2017-08-08 at 12 16 10 pm" src="https://user-images.githubusercontent.com/5863899/29087509-6f4c204a-7c33-11e7-98f3-605887ea8461.png">

3. With it closed, switch to schematic
4. Click it again and the highlight is of the "smaller" variant.
5. Keep the switch closed, and switch to normal view.
6. The highlight is "smaller". The size of this remains constant until switching between schematic/normal.

<img width="335" alt="screen shot 2017-08-08 at 12 16 21 pm" src="https://user-images.githubusercontent.com/5863899/29087524-7e7f5fb4-7c33-11e7-82e9-fa11ea974a20.png">

URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.135/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.135 2017-08-02 19:46:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
Language: en-US
Window: 1920x1012
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"0e3d5567","branch":"master"},"babel":{"sha":"51a4bd3b","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"6829432d","branch":"master"},"circuit-construction-kit-common":{"sha":"ee9efcbe","branch":"master"},"circuit-construction-kit-dc":{"sha":"5e5b0c9f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"8a235835","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"phet-core":{"sha":"d8bec6c1","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"9f5612d2","branch":"master"},"scenery-phet":{"sha":"23839a28","branch":"master"},"sherpa":{"sha":"be8e800b","branch":"master"},"sun":{"sha":"a56ba571","branch":"master"},"tandem":{"sha":"29cd4f63","branch":"master"},"twixt":{"sha":"3ca102d0","branch":"master"}}

**Comment by samreid** [comment]
Proposed fix published to http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.143/circuit-construction-kit-dc_en.html

@phet-steele can you please test?

**Comment by phet-steele** [comment]
Fixed.
