### ISSUE TITLE
Keep value text centered over a component

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#134]
@samreid, I spoke with @arouinfar and we think it would be nice to have values always centered over their component. This should also support dynamic changes of value width, so going from 9.5 V to 10.0 V (an extra character is added here) should stay centered around the same point. Can we see how this would look? Hopefully there aren't too many design challenges with this.

For phetsims/QA/issues/33.

**Comment by samreid** [comment]
The value text is centered on the components in this version:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.144/circuit-construction-kit-dc_en.html

@arouinfar and @phet-steele can you please review? Whichever version you prefer, please be specific about the pros and cons.

**Comment by arouinfar** [comment]
@samreid looks like there was a slight miscommunication. We wanted to keep the vertical offset, but center the label horizontally. Looks like you vertically centered the labels, but "10.0 Ω" and "9.0 Ω" labels are still have the same right alignment. 
![image](https://user-images.githubusercontent.com/8419308/29107617-3ad47c80-7c98-11e7-9bdd-da0454f4d0eb.png)

**Comment by samreid** [comment]
This is from version dev.143:

![image](https://user-images.githubusercontent.com/679486/29123312-8b55585c-7cd2-11e7-81f2-5761388672ae.png)

It seems the request is to put the label centered north of the midpoint of the component rather than offset from the local "up" coordinate in the coordinate frame of the circuit element.   I will take a look.

**Comment by arouinfar** [comment]
In dev.135 the labels look like this
![image](https://user-images.githubusercontent.com/8419308/29124844-4bc4bac0-7cd7-11e7-99cd-527e59d5a391.png)

The label on the "landscape" 9.5-ohm resistor isn't centered over the component, but the other labels look fine @samreid.

**Comment by samreid** [comment]
Proposed fix is http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.147/circuit-construction-kit-dc_en.html @arouinfar can you please test?

**Comment by arouinfar** [comment]
👍

**Comment by phet-steele** [comment]
@samreid sorry for the miscommunication! Looks like it was all sorted out. I'd to point out though, that the lightbulb value text is not initially centered when switching between schematic/normal. It takes some interaction to cause the text to update and recenter:

![cckdc14](https://user-images.githubusercontent.com/5863899/29133149-c4454c2c-7cef-11e7-9cf0-a76f41a0bbdc.gif)

This never happened in older versions since we didn't care to center the text (schematic view in old versions would just ALWAYS be un-centered for the lightbulb). @samreid, can the text position here update prior to interaction?

**Comment by samreid** [comment]
In this version, the text position updates when changing between lifelike/schematic: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.151/circuit-construction-kit-dc_en.html

@phet-steele can you please test?

**Comment by phet-steele** [comment]
It's beautiful!
