### ISSUE TITLE
Increase the size of the switch's infinity symbol

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#135]
@samreid, I spoke with @arouinfar and we think it would be nice if the infinity symbol for the open switch value text was larger. There are two problems with the current implementation:

- The symbol is small and hard to see when the play area is zoomed out
- The difference in the text size between open/closed (closed displaying "0.0 Ω") causes a horizontal jump in the text (the vertical jump is understandable and fine as is).

Increasing the size of the symbol would easily fix the first point. It would be nice, for the sake of the second point, if the size is made large enough such that the entire text has the same width as  "0.0 Ω". Keeping the text for closed and open the same width would keep the text horizontally aligned when switching states, no?

For phetsims/QA#33.

**Comment by samreid** [comment]
@jonathanolson said RichText can change fonts within a single string.

It may fix the second problem (widths) to use "0 Ω" instead of "0.0 Ω".

I also asked @jonathanolson for his recommendations on this issue.

**Comment by samreid** [comment]
> Font size of the infinity symbol on different platforms sounds problematic. Use a Path for it so it is consistent?

**Comment by samreid** [comment]
The current setup has the following advantages:
1. It is internationalizable using the following string:

```json
  "resistanceOhmsSymbol": {
    "value": "{{resistance}} Ω"
  },
```

2. PhET-iO clients will be able to read this as a text value.
3. The implementation is straightforward

Regarding the original reports:
> The symbol is small and hard to see when the play area is zoomed out

Most (all?) of the readouts are small and hard to see when the play area is zoomed out.  Why not increase the size for all of them?
![image](https://user-images.githubusercontent.com/679486/29103960-06102b92-7c80-11e7-8843-afffb971051d.png)

> The difference in the text size between open/closed (closed displaying "0.0 Ω") causes a horizontal jump in the text (the vertical jump is understandable and fine as is).

What about using "0 Ω" instead of "0.0 Ω" for this case?  Or would that be too inconsistent with other types of components?

**Comment by arouinfar** [comment]
@samreid "0 Ω" instead of "0.0 Ω" sounds good to me.

**Comment by arouinfar** [comment]
> Most (all?) of the readouts are small and hard to see when the play area is zoomed out. Why not increase the size for all of them?

I think the infinity symbol looks disproportionately small, and increasing the size of other readouts would look too large at the regular zoom level.

**Comment by samreid** [comment]
In the above commit, the switch should show `0 Ω`.

**Comment by samreid** [comment]
I tried changing the font for the entire readout, including the ohms symbol.  Here is regular zoom:
![image](https://user-images.githubusercontent.com/679486/29123062-b222e98c-7cd1-11e7-8f3d-707b8b73e33c.png)

and here is zoomed out:
![image](https://user-images.githubusercontent.com/679486/29123076-bc93a49c-7cd1-11e7-9f84-ae029ade3e55.png)

@arouinfar do you think something like that might work?

**Comment by samreid** [comment]
In the preceding change, the font is increased only for switches, and remains the same size for other components.

**Comment by samreid** [comment]
I decided to commit the change for increased Switch value font size, we can roll it back if we desire.

**Comment by samreid** [comment]
On second thought, this does look kind of odd:

![image](https://user-images.githubusercontent.com/679486/29123550-5bf4ef4a-7cd3-11e7-962e-d16e2859cb46.png)

Maybe I should try RichText...

**Comment by samreid** [comment]
This is RichText with Century Gothic and a font size bump for the infinity symbol for the switch and Arial for the other one:

![image](https://user-images.githubusercontent.com/679486/29124602-98e5a5d6-7cd6-11e7-8b72-75d0a33b359d.png)

**Comment by samreid** [comment]
'Century Gothic' renders as century gothic, but 'Century Gothic, Arial' renders as arial.  @jonathanolson can you help?

**Comment by samreid** [comment]
Proposed fix is http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.147/circuit-construction-kit-dc_en.html @arouinfar can you please test?

**Comment by arouinfar** [comment]
👍

**Comment by arouinfar** [comment]
While the switch looks ok, I realized while verifying #134 that this was effecting all components (thought it was just the switch).

I think the thinner numbers are actually a bit harder to read...
![image](https://user-images.githubusercontent.com/8419308/29128667-b6820c96-7ce1-11e7-9ada-6e2790e6b4af.png)

**Comment by arouinfar** [comment]
I think these numbers are Century Gothic @samreid. Maybe your browser was showing the fallback?

**Comment by samreid** [comment]
Yep, it looks like @arouinfar is showing Century Gothic and my machine was showing some fallback.

**Comment by samreid** [comment]
I went back to Arial, then selected bold serif for the infinity symbol: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.149/circuit-construction-kit-dc_en.html

@arouinfar and @phet-steele can you please test it out?

**Comment by arouinfar** [comment]
Much better @samreid! @phet-steele can you also take a look?

**Comment by phet-steele** [comment]
I like where this is at! Thanks for the suggestions and work, @arouinfar @samreid.
