### ISSUE TITLE
Can we layer the value text over highlights?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#136]
@samreid @arouinfar I'd like to at least raise discussion about the possibility of layering the value text over a highlight box/circle. Currently, I think this looks bad:

<img width="276" alt="screen shot 2017-08-08 at 12 47 06 pm" src="https://user-images.githubusercontent.com/5863899/29088854-c72602be-7c37-11e7-8db4-f303c19edc15.png">

Here is a poor-man's mockup of a layer change:

<img width="276" alt="screen shot 2017-08-08 at 12 47 06 pm" src="https://user-images.githubusercontent.com/5863899/29089053-4f608398-7c38-11e7-8709-6390da009e18.png">

I prefer the aesthetics of the latter, but I could be swayed either way.

For phetsims/QA#33.

**Comment by arouinfar** [comment]
Thanks for the mockups @phet-steele! Now that I see the value layered on top, I think it does indeed look nicer.

With the rectangle layered over the values, it's hard to see the voltage as it's being changed. (But one could argue that the user can get this information from the voltage slider's readout.)

@samreid if this is an easy change and won't wreak havoc on the layering simplifications you've already made, then I'd say go for it. Like @phet-steele, I could go either way on this one.

**Comment by samreid** [comment]
Values are in front of highlight starting in this version: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.142/circuit-construction-kit-dc_en.html

@phet-steele can you please check it?

**Comment by phet-steele** [comment]
Looks better, thanks guys!

**Comment by phet-steele** [comment]
Actually, let's have @arouinfar take a look.

**Comment by arouinfar** [comment]
:+1:
