### ISSUE TITLE
Controls for wire resistivity?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#14]
How should we control wire resistivity, if at all?

**Comment by arouinfar** [comment]
@samreid I believe we'll use a slider, like the Java version. Something like this, for example:
![image](https://cloud.githubusercontent.com/assets/8419308/23533427/f6e583a8-ff6e-11e6-94c9-8d65efb4fa86.png)

**Comment by arouinfar** [comment]
However, we haven't had a recent discussion about it in design meeting. I think it'd be good to bring it up again, so I'll leave this tagged for design meeting.

**Comment by arouinfar** [comment]
As discussed in 4/13/17 design meeting
![image](https://cloud.githubusercontent.com/assets/8419308/25024285/87e946b2-205a-11e7-821d-f301fc3a2e96.png)

**Comment by samreid** [comment]
This is implemented, closing.
