### ISSUE TITLE
pool charges in ChargeLayout

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#143]
From https://github.com/phetsims/circuit-construction-kit-dc/issues/140 we may be able to get a performance boost by pooling charges in the layout.  I'd like to check if that's possible/easy.

**Comment by samreid** [comment]
Fixed in preceding commit, and dragging one vertex of a wire is significantly faster on iPad2 now.  This will need to be tested in case it introduced any new issues.  Specifically, testing anything that could cause the creation or relayout of charges--dragging out a component, resizing a component, etc.  @phet-steele and/or @arouinfar can you please test http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.156/circuit-construction-kit-dc_en.html to make sure these features are still OK?

**Comment by samreid** [comment]
Hold everything, I'm seeing assertion errors when cutting a vertex...

**Comment by samreid** [comment]
Well, that problem seems unrelated, so I'll pursue it in another issue.  This version can still be tested (assertions removed in build).

**Comment by phet-steele** [comment]
@samreid looks good to me!

**Comment by arouinfar** [comment]
Thanks @phet-steele. Looks good to me too.
