### ISSUE TITLE
Google form user suggestion: add ohmmeter

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#145]
> i suggest adding ohmmeter to measure the equivalent resistor

**Comment by oliver-phet** [comment]
Assigning to @amyh-phet to decide if this is worth pursuing.

**Comment by arouinfar** [comment]
Sounds like the user may want to measure the effective resistance of a few resistors in series. Like so:

![image](https://user-images.githubusercontent.com/8419308/29685692-6ac998a2-88d3-11e7-8d51-da6c5cb2e9bd.png)

By measuring V and I in a circuit, the user could use Ohm's Law (or build equivalent circuits) to discover that the effective R = R1+R2
![image](https://user-images.githubusercontent.com/8419308/29686152-2d880cce-88d5-11e7-97de-7aa48bdd07ce.png)


Learning how to use an ohmmeter is not a learning goal of CCK, so there are no plans to create an ohmmeter for any of the sims in the CCK suite @oliver-phet.

**Comment by oliver-phet** [comment]
Email to user sent.
