### ISSUE TITLE
Assertion failure while attempting to disconnect light bulb in weird pattern

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/circuit-construction-kit-dc#147]
![cck-bug-1](https://user-images.githubusercontent.com/480878/29908465-bdb63790-8dde-11e7-80c5-497991f7eff2.PNG)

**Comment by samreid** [comment]
Not sure how how to reproduce this problem, can you provide steps?

**Comment by jonathanolson** [comment]
Can't reproduce now, closing (presumably things would come up in testing if it's a problem).
