### ISSUE TITLE
Light bulb not catching on fire

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#148]
Is it supposed to?

**Comment by samreid** [comment]
@arouinfar do you recall?

**Comment by arouinfar** [comment]
@samreid we discussed this a bit in https://github.com/phetsims/circuit-construction-kit-common/issues/72, and decided against having the light bulb catch fire.

@ariel-phet commented:
> @samreid I think keeping the lightbulb flames would be problematic. A resistor only heats up if it has resistance (P=I^2*R). So The battery is being short circuited, and probably assumed to have some small internal resistance, but if you are setting the lightbulb to no resistance, it should actually not get hot.

**Comment by samreid** [comment]
But is that statement only for a 0-resistance light bulb?

**Comment by arouinfar** [comment]
Possibly... but it was in response to your comment asking if lightbulbs should catch fire.

The current behavior matches Java, and personally, I think a fiery bulb looks really strange. In interviews, students interpreted the fire just fine, so I'm not inclined to change it.

**Comment by samreid** [comment]
OK thanks!  I'll finish removing the light bulb fire code.

**Comment by samreid** [comment]
Removed light bulb fire code, closing.
