### ISSUE TITLE
Improve touch areas

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#149]
@jonathanolson noted some deficiencies in the touch areas that would be good to improve upon:

- [x] labels and values checkboxes, should the touch/mouse area extend to the right?  @jonathanolson points out that there may be no principled way to do this and it may warrant a larger issue in sun or scenery.
- [x] voltmeter icon touch area should span the bounds.
- [x] ammeter icon touch area should span the bounds.
- [x] reset all button increase
- [x] zoom in out buttons increase
- [x] series ammeter icon has too wide touch area
- [x] in the circuit element edit panel, push the touch area down a bit

**Comment by samreid** [comment]
I updated the touch areas in the preceding commits, @jonathanolson would you please review?

**Comment by jonathanolson** [comment]
Looks good, thanks!
