### ISSUE TITLE
Animation speed limit reach inconsistency causes flashing of text

### ISSUE THREAD

**Issue by arnabp** [phetsims/circuit-construction-kit-dc#15]
For phetsims/tasks#765

I set up a 95 volt battery and a 4.5 ohm resistor in series. When turning on "show electrons" the text indicating that animation speed limit has been reach begins to flash as it fluctuates between 99% and 100%. This fluctuation happens any time animation speed is reduced, but when getting a sim to the breaking point it's most apparent and can be irritating to the user.

Easiest solution appears to me to be to remove the fluctuation and have the simulation speed reduction only change when the user changes parameters of the simulation.

**Comment by samreid** [comment]
The problem is that the dt value of the simulation naturally fluctuates, this is already averaged and clipped, but we may need to add specific logic in this message that makes it only possible to change every 500ms or so.

**Comment by samreid** [comment]
Likewise, it could fluctuate between any two numbers.  It would be good to eliminate all kinds of fluctuation.

**Comment by samreid** [comment]
> Easiest solution appears to me to be to remove the fluctuation and have the simulation speed reduction only change when the user changes parameters of the simulation.

Good idea, perhaps if we factor out the dt from this setting it can be more deterministic.

**Comment by samreid** [comment]
Proposed fix is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.35/circuit-construction-kit-dc_en.html

@phet-steele can you please test or delegate?

**Comment by phet-steele** [comment]
I haven't seen any flashing, I think it's fixed. Thanks @samreid.
