### ISSUE TITLE
Some images have shifted

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#150]
Did they get shifted on purpose? The first version where these are moved is dev.158. I only see this on the hand and dog.

1.0.0-dev.160:
<img width="414" alt="screen shot 2017-09-08 at 11 31 27 am" src="https://user-images.githubusercontent.com/5863899/30223833-b1bb17f6-9489-11e7-98c7-46dcb7f115ac.png">

1.0.0-dev.157 (presumably correct):
<img width="390" alt="screen shot 2017-09-08 at 11 34 26 am" src="https://user-images.githubusercontent.com/5863899/30223834-b1bbf0ae-9489-11e7-9d21-0e75d9044736.png">

1.0.0-dev.160:
<img width="315" alt="screen shot 2017-09-08 at 11 37 48 am" src="https://user-images.githubusercontent.com/5863899/30224013-4fe02f52-948a-11e7-9fad-0a063a8be413.png">

1.0.0-dev.157 (presumably correct):
<img width="357" alt="screen shot 2017-09-08 at 11 37 53 am" src="https://user-images.githubusercontent.com/5863899/30224014-4fe5db28-948a-11e7-932f-68baf25ab2f7.png">

Seen on macOs 10.12.6 Chrome. For phetsims/QA/issues/48.

URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.160/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.160 2017-09-07 18:03:16 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"7083c475","branch":"master"},"babel":{"sha":"5b127384","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"66110366","branch":"master"},"circuit-construction-kit-common":{"sha":"a165d9ef","branch":"master"},"circuit-construction-kit-dc":{"sha":"2722c8da","branch":"master"},"dot":{"sha":"630fb098","branch":"master"},"joist":{"sha":"f51d5ab4","branch":"master"},"kite":{"sha":"dc5c4382","branch":"master"},"phet-core":{"sha":"30da7870","branch":"master"},"phetcommon":{"sha":"1a5ceb11","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"fc2d1cf1","branch":"master"},"scenery-phet":{"sha":"55f204d3","branch":"master"},"sherpa":{"sha":"e29820c9","branch":"master"},"sun":{"sha":"1ed8afa5","branch":"master"},"tandem":{"sha":"37243b99","branch":"master"},"twixt":{"sha":"6f27c1ff","branch":"master"}}

**Comment by samreid** [comment]
Thanks @phet-steele, dev.157 is correct, I'll see what's happened here.

**Comment by samreid** [comment]
Fixed in preceding commit, @phet-steele would you like a new version?

**Comment by phet-steele** [comment]
> @phet-steele would you like a new version?

Nope!

Fixed in master.
