### ISSUE TITLE
components are only visible on bottom left part of screen for Edge

### ISSUE THREAD

**Issue by BryceAG** [phetsims/circuit-construction-kit-dc#153]
related to phetsims/QA#48.

Test device:
Hanson
Operating System:
Windows 10
Browser:
Edge
Problem description:
The components are not visible until dragged to a portion of the screen in the lower left. Taking a screenshot using the phet menu shows everything as normal, but it doesn't show up on screen that way. The voltmeter and first ammeter show up, but only the text box of the 2nd ammeter shows up outside of the component area. Components can still be clicked and function correctly, and the lightbulbs lights still show.
Steps to reproduce:
drag a component
Screenshots:
This was taken using snipping tool, I used wires to show the boundary area, and turned on values to show where other things should be:
![image](https://user-images.githubusercontent.com/15327201/30234902-5201c806-94bf-11e7-9d8f-58f11dabde42.png)

This was taken using the screenshot from the phet menu, and shows nothing wrong:
![circuit construction kit_ dc screenshot 1](https://user-images.githubusercontent.com/15327201/30234849-c53cb4c6-94be-11e7-8534-0ea64fc5cfcc.png)

Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: DC‬
URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.160/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.160 2017-09-07 18:03:16 UTC
Features missing: touch
Flags: pointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
Language: en-US
Window: 1280x604
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"7083c475","branch":"master"},"babel":{"sha":"5b127384","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"66110366","branch":"master"},"circuit-construction-kit-common":{"sha":"a165d9ef","branch":"master"},"circuit-construction-kit-dc":{"sha":"2722c8da","branch":"master"},"dot":{"sha":"630fb098","branch":"master"},"joist":{"sha":"f51d5ab4","branch":"master"},"kite":{"sha":"dc5c4382","branch":"master"},"phet-core":{"sha":"30da7870","branch":"master"},"phetcommon":{"sha":"1a5ceb11","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"fc2d1cf1","branch":"master"},"scenery-phet":{"sha":"55f204d3","branch":"master"},"sherpa":{"sha":"e29820c9","branch":"master"},"sun":{"sha":"1ed8afa5","branch":"master"},"tandem":{"sha":"37243b99","branch":"master"},"twixt":{"sha":"6f27c1ff","branch":"master"}}

**Comment by samreid** [comment]
@jonathanolson any idea what is happening here?  The renderer should be SVG only (no webgl in this version).  Do we sometimes put `canvas` as the renderer for Edge?

**Comment by jonathanolson** [comment]
> The renderer should be SVG only (no webgl in this version). Do we sometimes put canvas as the renderer for Edge?

The default in Joist is always Canvas for Edge. Is this being overridden to specify SVG (probably not recommended, due to potential for text bugs in the menu and other places)?

That shouldn't cause rendering issues normally though, I'll look into it.

**Comment by jonathanolson** [comment]
Can reproduce with rootRenderer=canvas.

**Comment by jonathanolson** [comment]
Looks like an SVG element is still being created. There's a root-level `<svg>` whose bounds are what is being clipped, so it should be related to that.

**Comment by jonathanolson** [comment]
rootRenderer=canvas&showFittedBlockBounds is showing:

![cck-bounds](https://user-images.githubusercontent.com/480878/30308847-33a696ec-9745-11e7-9b01-7d180fc4b5b1.PNG)

**Comment by jonathanolson** [comment]
> Looks like an SVG element is still being created. There's a root-level <svg> whose bounds are what is being clipped, so it should be related to that.

That was the SVG for the overlay, so red herring.

**Comment by samreid** [comment]
Putting edge's rootRenderer as `svg` instead of canvas in Sim.js fixes the problem, but then there are text issues:

![image](https://user-images.githubusercontent.com/679486/30333734-e9d1bd84-979a-11e7-8712-b78fb5bd12e5.png)

**Comment by samreid** [comment]
Putting renderer 'webgl' in CircuitLayerNode.js and leaving canvas for the text appears to fix the problem.

**Comment by jonathanolson** [comment]
> Putting renderer 'webgl' in CircuitLayerNode.js and leaving canvas for the text appears to fix the problem.

Understood, but it is indicative of a Scenery bug in general that I'd like to get fixed, and we'll want Canvas for Edge on the text.

**Comment by jonathanolson** [comment]
Fixed in Scenery, @samreid can you verify?

**Comment by samreid** [comment]
I pulled and tested in my virtualbox edge, it seems good, thanks!

**Comment by samreid** [comment]
@BryceAG can you confirm this on phettest?

**Comment by BryceAG** [comment]
This is still an issue on Hanson through phettest.

**Comment by BryceAG** [comment]
scratch that, scenery wasn't pulled, It is fixed!
