### ISSUE TITLE
Electrons icon seems large

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-dc#154]
In the control panel the electrons icon seems large. The icon is larger than the default size of electrons in the sim. I would consider reducing the icon to at least match the default electron size.

![electrons](https://user-images.githubusercontent.com/4051174/30282628-0e904d16-96d3-11e7-9f5e-b63b55fdcaa1.PNG)

**Comment by arouinfar** [comment]
Great idea @ariel-phet. It does seem a bit too large now. @samreid can you update the icon to match the new electron size?

**Comment by samreid** [comment]
Fixed in the preceding commit and available for review in master on phettest, or let me know if you'd like to see a new dev version.

**Comment by samreid** [comment]
Also, here's a pic after the change with an adjacent battery + electrons for scale: 
![image](https://user-images.githubusercontent.com/679486/30306344-d0cb976c-9734-11e7-8b71-1bff74002482.png)

**Comment by ariel-phet** [comment]
Looks good. Closing
