### ISSUE TITLE
User suggestion: pluggable ammeter

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#155]
> Great job on the new sim! Might I suggest including a pluggable ammeter, in addition to the current probe? One of the key take-aways in circuit investigations is the right way vs the wrong way -and why-  to wire in a voltmeter and ammeter into a circuit, and the changes in behavior that result from the wrong way.

**Comment by ariel-phet** [comment]
@oliver-phet can you tell the user to simply look at the "lab" screen. That screen includes an in line (pluggable) ammeter

**Comment by oliver-phet** [comment]
Will do. Closing.
