### ISSUE TITLE
User reported issue: freezing

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#156]
> Fantastic update, unfortunately the program stalls after a few basic circuits are set, maybe my machine but I have not had this problem before with the circuit program.

![image](https://user-images.githubusercontent.com/5090275/30442836-e5ba93a0-993a-11e7-9f3f-a6e639893e6c.png)

Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: Prototype
URL: https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.157 2017-08-25 17:25:34 UTC
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; Tablet PC 2.0; rv:11.0) like Gecko
Language: en-AU
Window: 1366x673
Pixel Ratio: 1/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"62935a11","branch":"HEAD"},"babel":{"sha":"3a7206f3","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"d94eda87","branch":"HEAD"},"circuit-construction-kit-common":{"sha":"a46405df","branch":"HEAD"},"circuit-construction-kit-dc":{"sha":"6800df7f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"HEAD"},"joist":{"sha":"cc9b9d62","branch":"HEAD"},"kite":{"sha":"dc5c4382","branch":"HEAD"},"phet-core":{"sha":"6bfeef5c","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"41bc57fb","branch":"HEAD"},"scenery-phet":{"sha":"b2cd8624","branch":"HEAD"},"sherpa":{"sha":"dba01386","branch":"HEAD"},"sun":{"sha":"50f640e7","branch":"HEAD"},"tandem":{"sha":"74233a04","branch":"HEAD"},"twixt":{"sha":"6f27c1ff","branch":"HEAD"}}

**Comment by oliver-phet** [comment]
A second report of this issue:

Test device:              HP Probook intel i5-4200M
 
Operating System:   Windows 10 Education version 1703
 
Browser:                   Internet Explorer 11, version 11.540.15063.0
 
Problem description: Program freezes after 2-3 components are added into a circuit. After a while, all the changes I have make while the window is “frozen” suddenly appears.
 
Steps to reproduce: Start program, add 2 or more components, connect them to each other.
 
Severity:                    Program unusable
 
Screenshots:            I have not made a screenshot.
 
Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: Prototype
URL: https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.157 2017-08-25 17:25:34 UTC
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko
Language: da-DK
Window: 1348x663
Pixel Ratio: 1/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"62935a11","branch":"HEAD"},"babel":{"sha":"3a7206f3","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"d94eda87","branch":"HEAD"},"circuit-construction-kit-common":{"sha":"a46405df","branch":"HEAD"},"circuit-construction-kit-dc":{"sha":"6800df7f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"HEAD"},"joist":{"sha":"cc9b9d62","branch":"HEAD"},"kite":{"sha":"dc5c4382","branch":"HEAD"},"phet-core":{"sha":"6bfeef5c","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"41bc57fb","branch":"HEAD"},"scenery-phet":{"sha":"b2cd8624","branch":"HEAD"},"sherpa":{"sha":"dba01386","branch":"HEAD"},"sun":{"sha":"50f640e7","branch":"HEAD"},"tandem":{"sha":"74233a04","branch":"HEAD"},"twixt":{"sha":"6f27c1ff","branch":"HEAD"}}

**Comment by samreid** [comment]
I suspect this was fixed by https://github.com/phetsims/circuit-construction-kit-dc/issues/163

@phet-steele can you take a look and see if you agree?

**Comment by phet-steele** [comment]
Oh most certainly #163 was the issue, thanks @samreid. @oliver-phet, I suppose you could email these people (or not) and say the provided version is not supported on IE, but the full release version will be.

**Comment by oliver-phet** [comment]
Email to user sent. Closing.
