### ISSUE TITLE
User suggestion: Lightbulb and ammeter settings

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#157]
> One thing would improve this model a lot for using it in my classes  and that's the behaviour of the lightbulb.
> It now behaves like an ideal resistor, could you make it behave more like an actual lightbulb (e.g. a PTC?). 
> As it is, I need to explain why it (the model) doesn't (as the students find out when the conduct their experiments).
> 
> Having said that: 
> The Ameter could use a resistance setting (useful if you need to simulate experiments on constantan wires). Same applies to V-meters for different reasons.

**Comment by arouinfar** [comment]
@oliver-phet we are planning to add a non-Ohmic bulb to CCK, as it's been a very popular user request over the years. However, it won't be included the 1.0 release (see https://github.com/phetsims/circuit-construction-kit-common/issues/10). 

> Having said that:
The Ameter could use a resistance setting (useful if you need to simulate experiments on constantan wires). Same applies to V-meters for different reasons.

Not sure I follow this part of the user's request. I think they're requesting internal resistance in the ammeter and voltmeter. If so, the Wire Resistivity and Battery Resistance controls on the Lab screen may address the user's goals.

**Comment by oliver-phet** [comment]
Reply to user sent.

**Comment by oliver-phet** [comment]
I'll close this for now.
