### ISSUE TITLE
Electrons and conventional current should animate at the same speed

### ISSUE THREAD

**Issue by BryceAG** [phetsims/circuit-construction-kit-dc#160]
related to phetsims/QA#51, and discussed in phetsims/circuit-construction-kit-dc#62

The iPad 2 will start performing well at 40-60 fps, but will quickly dip to 30 fps (which is still fine) with even a simple battery and light bulb circuit, and 20 fps with a simple parallel circuit. when moving objects around it seems that 20 fps is the max, and after completing any circuit it will stay there for a few seconds. A complex circuit such as the one shown below will result in 3 fps.

![image](https://user-images.githubusercontent.com/15327201/31029001-483695d2-a50d-11e7-9faf-88a3fd9a62ef.png)

Also interesting to note is that performance increased in schematic mode over realistic mode, and conventional current over electrons.

Assigning to @ariel-phet to decide if this should be addressed.

**Comment by ariel-phet** [comment]
@samreid obviously with a circuit as complicated as above I am not surprised at a pretty serious performance hit.

However, I am a bit concerned about the difference in performance between conventional current and the electron view. I made a not too complex circuit (a few batteries, a resistor 2 bulbs), and the difference between the speed of conventional current and the electrons is very noticeable. Since these currents are equivalent in value, just in different directions, it could be pedagogically confusing/damaging to have the representations show different behavior in terms of speed. It makes it look like there is "more" conventional current.

It seems a good place to start would be to understand why conventional current is showing so much better performance.

**Comment by samreid** [comment]
@ariel-phet what platform did you use to identify that problem?

**Comment by ariel-phet** [comment]
@samreid iPad 2 as noted in the issue

**Comment by samreid** [comment]
I suspect the difference is due to transparency.  Electrons are fully opaque while the arrows use `setImageOpacity` of `0.75`.  I would have expected this difference when using `setOpacity` but not `setImageOpacity`, @jonathanolson does this match your expectation?

Image transparency is pretty much "free" in WebGL, we may be seeing new differences since we are rendering in SVG now.

Brainstorming a hack that would line up the performance of each (if the difference is indeed attributable to the different `imageOpacity` values: we could put the electron opacity at 0.9999.  But let's wait to hear from @jonathanolson first.

Another possibility would be to rasterize the arrow as a PNG which already includes the transparency, then in the code to render it with imageOpacity = opacity = 1.

**Comment by ariel-phet** [comment]
@samreid well since the arrows are performing better, if we make a hack, lets make it ideally in the direction where both the electrons and arrows perform at the current arrow level.

**Comment by jonathanolson** [comment]
> Another possibility would be to rasterize the arrow as a PNG which already includes the transparency, then in the code to render it with imageOpacity = opacity = 1.

That might be worth the experimentation. First, I'd check to see that opacity is what is causing the performance loss.

**Comment by samreid** [comment]
Here is other code in ChargeNode.js that may lead to differences in runtime behavior on the iPad2

```js
      if ( charge.charge > 0 ) {

        // Rotate if current is running backwards
        ( current < 0 ) && NODE_MATRIX.multiplyMatrix( HALF_ROTATION );

        // Center
        NODE_MATRIX.multiplyMatrix( ARROW_OFFSET );

        // Apply the transform
        this.matrix = NODE_MATRIX;

        var opacity = Util.linear( 0.015, CONVENTIONAL_CHARGE_THRESHOLD, 1, 0, Math.abs( charge.circuitElement.currentProperty.get() ) );
        opacity = Util.clamp( opacity, 0, 1 );
        this.setImageOpacity( opacity );
      }
      else {

        // Set rotation to 0 since electrons should always be upside-up
        NODE_MATRIX.set00( 1 );
        NODE_MATRIX.set01( 0 );
        NODE_MATRIX.set10( 0 );
        NODE_MATRIX.set11( 1 );

        // Center the electrons
        NODE_MATRIX.multiplyMatrix( ELECTRON_OFFSET );

        // Apply the transform
        this.matrix = NODE_MATRIX;
      }
```

**Comment by samreid** [comment]
I made a long loop with 1.0 ohm resistor + 9V battery and measured about 8 seconds for electron to traverse vs 5 seconds for arrow to traverse vertically.

**Comment by samreid** [comment]
Removing this code seems to align the performances:

```js
    // Negative charges should be transparent
    this.setImageOpacity( charge.charge < 0 ? 0.75 : 1 );
```

I noticed that electrons already attempted 0.75 opacity in their constructor:

```js
  var ELECTRON_CHARGE_NODE = new ElectronChargeNode( {

    // electrons are transparent to signify they are just a representation, not physical electrons
    opacity: 0.75,

    // selected so an electron will exactly fit the width of a wire
    scale: 0.78
  } ).toDataURLImageSynchronous();
```

But this opacity doesn't seem to be respected--I tried setting it to 0.75*0.75=0.56 and they looked fully opaque.  It should be easy enough to create a electron raster PNG with correct opacity and use it, but we should also understand why this is a problem.  For example, if toDataURLImageSynchronous doesn't support opacity or if I'm doing something else wrong.  We are also using common code to render the electron which will keep it in sync across simulations if there are any changes--a CCK-specific raster would allow it to accidentally deviate (maybe one day).

**Comment by samreid** [comment]
If I try:

```js
  // constants
  var electronChargeNode = new ElectronChargeNode( {

    // electrons are transparent to signify they are just a representation, not physical electrons
    opacity: 0.75,

    // selected so an electron will exactly fit the width of a wire
    scale: 0.78
  } );
```
Then immediately try `ELECTRON_CHARGE_NODE.toDataURL(function(x){console.log(x);});` it comes up blank.

If I try:

```js
  // constants
  var electronChargeNode = new ElectronChargeNode( {

    // electrons are transparent to signify they are just a representation, not physical electrons
    opacity: 0.75,

    // selected so an electron will exactly fit the width of a wire
    scale: 0.78
  } );
  electronChargeNode.setOpacity( 0 );
  var ELECTRON_CHARGE_NODE = electronChargeNode.toDataURLImageSynchronous();
  window.E = ELECTRON_CHARGE_NODE;
```
then wait until launch then try `E.toDataURL(function(x){console.log(x);});` it comes out like so:

![image](https://user-images.githubusercontent.com/679486/31113213-622788b4-a7d5-11e7-922d-23a2b4f2f53e.png)

@jonathanolson am I doing something wrong?

**Comment by samreid** [comment]
I tried 
```js
  var ELECTRON_CHARGE_NODE = new ElectronChargeNode( {

  } ).toCanvas(function(c){
    console.log(c.toDataURL());
  });
```

Then in photoshop, applying 0.75 opacity and reducing size to 16px by 16px.  This fixes the performance difference.  The right edge of the electron looks slightly wonky though, it is coming out like this even though I left ample padding in the scenery generation and in the photoshop step:
![image](https://user-images.githubusercontent.com/679486/31114080-95b8e2aa-a7d9-11e7-89ad-6b77b37f7223.png)

**Comment by samreid** [comment]
If I put transparency in the shaded sphere and minus sign instead of the parent node, it looks good and toDataURLNodeSynchronous retains the transparency, and there are no odd artifacts:

![image](https://user-images.githubusercontent.com/679486/31114245-4db47df6-a7da-11e7-8d2f-ec2edf8ada29.png)

**Comment by samreid** [comment]
The commits above add a workaround for ElectronChargeNode. It will be nice to discuss with @jonathanolson about why opacity on the parent wasn't working, but this workaround is straightforward enough that we could proceed with it.  It is working well in my testing.

Leaving assigned to @jonathanolson for discussion about the opacity on the parent, and also assigning to @BryceAG or @ariel-phet to test the conventional vs electron current speed on phettest (and confirm electrons still look ok).

**Comment by samreid** [comment]
Dev version published here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.163/circuit-construction-kit-dc_en.html

**Comment by ariel-phet** [comment]
Speeds on iPad2 now appear to match, electron performance is improved, and electrons still look good.

Closing

**Comment by phet-steele** [comment]
> Speeds on iPad2 now appear to match, electron performance is improved, and electrons still look good.

Agreed, but keeping open for this maybe?:



> Leaving assigned to @jonathanolson for discussion about the opacity on the parent,

**Comment by ariel-phet** [comment]
@phet-steele that seems like it should be a separate issue, but yes, probably have @samreid move that issue somewhere else appropriate and close this one.

**Comment by samreid** [comment]
I created a new scenery issue and will close this one, thanks.
