### ISSUE TITLE
Wires do not delete properly

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/circuit-construction-kit-dc#161]
For phetsims/QA#51
Testing in phettest, after the commit made in https://github.com/phetsims/circuit-construction-kit-common/issues/281#issuecomment-332902739

Test device: Dirac, Hanson

Operating System: macOS 10.12, Win 10

Browser: Chrome, Safari, Firefox

Problem description: Deleting a wire via the trashcan button leaves the wire on the screen, its vertices sort of stay connected to other objects, and if you move the other object, the wire's electrons move with it as if it were still connected, but the wire does not move. Reset all does not fix it, and you will likely not be able to drag anything else out of the bar on the left without refreshing the page. 
There seem to be a lot of different problems that stem from this that @BryceAG and I are finding, but we may not cover them all, but here's what we have so far. After deleting one wire, you aren't able to select other wires to delete them. But we noticed that if you click a wire, then drag an object it's connected to, it will become highlighted yellow, but no trashcan icon will appear. 

Steps to reproduce: 
This can be done by just dragging out a single wire and deleting it. Or connecting it to a battery or other object, then deleting the wire and dragging the object. Or completing a full circuit then deleting the wire. Will be adding gifs below for more clarity momentarily. 

Severity: High

Troubleshooting information (do not edit):
Name: ‪Circuit Construction Kit: DC‬
URL: http://phettest.colorado.edu/circuit-construction-kit-dc/circuit-construction-kit-dc_en.html?ea&brand=phet
Version: 1.0.0-dev.162 (require.js)
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0
Language: en-US
Window: 1166x631
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 16 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by phet-steele** [comment]
Muahahahahaha I beat you to it by a few minutes! See https://github.com/phetsims/circuit-construction-kit-common/issues/406. This should be fixed in master as of recently. @brroberts1231 please hard refresh your page and try again (I already pulled). If it's gone, please close.

**Comment by brroberts1231** [comment]
Ok, literally within 10 minutes of writing that up, and going back to try to record more gifs, it stopped happening, haha. 
Can't reproduce, so I guess I'll close this.
