### ISSUE TITLE
Update Lab screen icon

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#162]
#88 rotated the voltmeter probes. @samreid @arouinfar, does this mean we should update the Lab screen icon? The icon's probes are still not rotated. https://github.com/phetsims/circuit-construction-kit-dc/blob/master/images/lab-screen-icon.png

For phetsims/QA/issues/51.

**Comment by samreid** [comment]
It looks like this was generated from the sim, I can try to update it.

**Comment by arouinfar** [comment]
Sounds good. Thanks @samreid.

**Comment by samreid** [comment]
Updated in the preceding commit, @arouinfar can you please review on phettest?

**Comment by arouinfar** [comment]
@phet-steele and I approve! Thanks @samreid.
