### ISSUE TITLE
IE crashes when completing a circuit

### ISSUE THREAD

**Issue by BryceAG** [phetsims/circuit-construction-kit-dc#163]
Related to phetsims/QA#51

Test device:
Bates

Operating System:
Windows 7

Browser:
Internet Explorer

Problem description:
In internet explorer, the display will freeze every time a circuit is completed, or sometimes randomly before you can even complete a circuit. This is true for both dev.162 and phettest. The sim is still interactive because I was able to click where "Report a problem..." was while frozen, but it does not show any changes.

Steps to reproduce:
complete a circuit

Troubleshooting information (do not edit):
  
Name: ‪Circuit Construction Kit: DC‬

URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.162/circuit-construction-kit-dc_en.html

Version: 1.0.0-dev.162 2017-09-19 15:30:35 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

Language: en-US

Window: 1366x674

Pixel Ratio: 1/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"3da47e60","branch":"listeners"},"babel":{"sha":"8024993e","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"chipper":{"sha":"beecf7e3","branch":"master"},"circuit-construction-kit-common":{"sha":"b0a1151d","branch":"master"},"circuit-construction-kit-dc":{"sha":"0b1708fd","branch":"master"},"dot":{"sha":"d2a1e0db","branch":"master"},"joist":{"sha":"4ac9bf9d","branch":"master"},"kite":{"sha":"5a200449","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"5b0c8dd6","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"b7e4a6a4","branch":"master"},"scenery-phet":{"sha":"f8b1c996","branch":"master"},"sherpa":{"sha":"f0d5f750","branch":"master"},"sun":{"sha":"569ad84b","branch":"master"},"tandem":{"sha":"3b161ec8","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by phet-steele** [comment]
@BryceAG please open the console and look for errors (on phettest).

**Comment by BryceAG** [comment]
States:
```
SCRIPT438: Object doesn't support property or method 'sign'
File: ChargeAnimator.js, Line: 215, Column: 9
```

**Comment by phet-steele** [comment]
Thanks @BryceAG.

This is too bad @samreid, support of Math.sign() doesn't exist in IE:
<img width="569" alt="screen shot 2017-10-04 at 2 33 48 pm" src="https://user-images.githubusercontent.com/5863899/31198345-27bf2f82-a911-11e7-91a9-15b27f781910.png">

**Comment by samreid** [comment]
Nice detective work @BryceAG and @phet-steele.  I added a new lint rule that will catch future usage of Math.sign (I also saw one usage in another unreleased sim.)

**Comment by samreid** [comment]
I added Util.sign from the MDN polyfill.  @BryceAG can you test on phettest?

**Comment by phet-steele** [comment]
@BryceAG isn't working today so I took a look. It doesn't crash when I make a circuit!
