### ISSUE TITLE
1.0 Screenshot

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#165]
@arouinfar, please suggest some.

See phetsims/QA/issues/55.

**Comment by arouinfar** [comment]
Here are a few options @phet-steele:

1. ![screen shot 2017-10-17 at 12 14 07 pm](https://user-images.githubusercontent.com/8419308/31682589-cfeb244c-b337-11e7-9d55-f46c1151f5a8.png)
2.  ![screen shot 2017-10-17 at 12 16 56 pm](https://user-images.githubusercontent.com/8419308/31682599-d6c81a36-b337-11e7-823b-bb0ccfb58e67.png)
3.  ![screen shot 2017-10-17 at 12 28 21 pm](https://user-images.githubusercontent.com/8419308/31682607-dbdc2ed6-b337-11e7-97b4-1415ec4ab13a.png)
4.  ![screen shot 2017-10-17 at 12 34 14 pm](https://user-images.githubusercontent.com/8419308/31682615-e0df1f24-b337-11e7-8ee5-c5c771c90174.png)


I think (1) is best for the main screenshot. I tried to show off a variety of features in the other screenshots, but I'm definitely open to any suggestions you may have @phet-steele!

**Comment by phet-steele** [comment]
@samreid @arouinfar, added above. (@arouinfar looked it over with me)
