### ISSUE TITLE
Publish 1.0

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#169]
CCK DC finished RC testing and is ready for publication as 1.0.  However, this will be more complicated than a normal deployment because there is an existing prototype at the target location, see https://github.com/phetsims/circuit-construction-kit-dc/issues/6 and https://github.com/phetsims/circuit-construction-kit-dc/issues/46

@mattpen can we coordinate on the release process to avoid complications or interference with the existing prototype?

**Comment by samreid** [comment]
My main questions about what may need attention:
1. the filesystem
2. the htaccess
3. the database (not sure about that one)

**Comment by samreid** [comment]
I asked @mattpen on slack: 

> Greetings, do I need your help in publishing CCK DC?  I recall there is already something in that spot called the prototype.

He replied:

> Hey Sam, I don't think so, but I'd be happy to help with the deploy since the RC had problems.  I'm 100% confident that if there are problems they won't be publicized on the website, and I'm reasonably confident there won't be any problems at all. Will it be ready Monday? Maybe we could work on it between or after meetings?

**Comment by samreid** [comment]
It is ready when we are, it sounds like I am approved to just try the normal process and report back if any problems occur.

**Comment by mattpen** [comment]
> It sounds like I am approved to just try the normal process and report back if any problems occur.

Yes, this is OK with me.

**Comment by phet-steele** [comment]
> He also points out that no other sims have those yet.

Sure they do! A decent handful do in https://github.com/phetsims/tasks/issues/779!

I'll take the extra screenshots momentarily, but true we do not need to halt publication until then.

**Comment by samreid** [comment]
I ran the deploy steps and now it is up to @arouinfar to add the metadata and make the sim visible.

**Comment by arouinfar** [comment]
On it @samreid! Did you also deploy Virtual Lab?

**Comment by samreid** [comment]
Nope, I won't have time for VL before meetings start today.  I'll create a separate issue for that one and pursue it later on.

**Comment by samreid** [comment]
I finished the deploy steps for CCK, unassigning myself and @arouinfar can proceed to add metadata and make visible.

**Comment by arouinfar** [comment]
The sim is now visible! I'll send out an announcement email once VL is live too.
