### ISSUE TITLE
Examining when fire should turn on

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/circuit-construction-kit-dc#17]
I was just playing with current HTML DC and original DC, and I noticed that in the original, you could vary voltage by the entire slider range ... and it was only upon going to "more volts" that you could get the fire to come on. We know students slide these sliders back and forth to the extremes, so I think we should decide if we want the fire to appear on the basic interaction. To me, it seemed nice to not have the fire come on with this basic one bulb, one resistor system at first ... so I wasn't distracted by that fire and just focused on the bulb brightness behavior. (The reason for the difference is the change in the default value of the light bulb resistor from 10 ohms to 4.5 ohms). 

This is a conversation for as we move forward with DC design. Current behavior is fine for prototype, but lets discuss at design sometime. Perhaps we should consider reducing the default range for the voltage slider - but of course that itself with have its own consequences.

**Comment by kathy-phet** [comment]
@arouinfar - Just tagging you on this one for discussion later.

**Comment by samreid** [comment]
@arouinfar can you consider @kathy-phet's thoughts above and make a recommendation?

**Comment by arouinfar** [comment]
@samreid as far as I understand, @kathy-phet's concerns in https://github.com/phetsims/circuit-construction-kit-dc/issues/17#issue-210109855 all stem from the 4.5 ohm default resistance. By bumping up the default resistance to 10 ohms, the fire will not appear in a simple one battery, one resistor (10 ohm) circuit, even if the voltage is increased to 100 V.

@kathy-phet can you please take a look at this issue and clarify?

**Comment by arouinfar** [comment]
Pinging @kathy-phet.

**Comment by samreid** [comment]
Labeling for design meeting in case @kathy-phet hasn't had a chance to investigate before then.

**Comment by arouinfar** [comment]
Discussed 6/15/17 and no further work needs to be done.
