### ISSUE TITLE
User suggestion: water analogy

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#173]
> In an effort to provide a concrete analogy to electrical circuits I create an analogy comparing an electrical circuit to a water circuit (as is commonly done of course). My idea is to have a hidden option (that only the teacher would know at first) where, upon activating this "water-analogy" option, the electrical components would change to their analogical components in a water circuit, similar to what happens when one goes back and forth between the realistic and schematic views of the circuit.
> 
> That this option would be hidden, revealed by some key-combination or something, would be helpful for those of us who do a conceptual change model AND have the students first use the physical components then move to the sim for further elaboration/visualization.

**Comment by arouinfar** [comment]
@oliver-phet this is waaaaaay beyond the scope of CCK, and would take significant design and development resources. If we did want to tackle the water/electric circuit analogy, I think it would be its own sim, not a hidden option buried somewhere. Can you add this to the ideas for sims on Unfuddle?

**Comment by oliver-phet** [comment]
Done.
