### ISSUE TITLE
'grunt published-README' was not run in 1.0 branch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-dc#174]
The 1.0 branches of the this sim still indicates that the sim is unpublished.

The master checklist for sims says:

> - [ ] README.md updated using `grunt published-README` (in master and release branch)

**Comment by ariel-phet** [comment]
marking for developer meeting as we are soon to publish a few sims

**Comment by pixelzoom** [comment]
Moving developer meeting label to the more general issue, https://github.com/phetsims/chipper/issues/698.

**Comment by samreid** [comment]
The README is correct on master, and on the 1.0 and 1.1 branches, closing.
