### ISSUE TITLE
is the ancestor program (pre HTML) available anywhere?

### ISSUE THREAD

**Issue by gartha1** [phetsims/circuit-construction-kit-dc#175]
is the ancestor program , previous version before it went HTML based, available anywhere?

**Comment by arouinfar** [comment]
@gartha1 to access the Java version of the simulation, click the "[Original Sim and Translations](https://phet.colorado.edu/en/simulation/legacy/circuit-construction-kit-dc)" link on the sim page. 

![image](https://user-images.githubusercontent.com/8419308/49392444-afae8e00-f6eb-11e8-8a57-a511b50c4f8c.png)
