### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-dc#178]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Pointer areas of objects not visible in the carousel tool box still show up on the second screen, but not the first, which seems odd to me

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56240851-acd88800-6051-11e9-93e5-2bf3b977b302.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56240852-acd88800-6051-11e9-9c0a-1a89660d313b.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56240853-acd88800-6051-11e9-9e3b-9db6808082ab.png)

**Comment by arouinfar** [comment]
Thanks @KatieWoe, this does look a bit odd. @samreid can you take a look?

**Comment by KatieWoe** [comment]
It is in the lab sim as well.  Doesn't seem to have an effect.

**Comment by samreid** [comment]
Cross-assigning to @pixelzoom who knows more about Carousel and @jonathanolson who knows more about pointer areas.  Any idea what is happening here?

**Comment by pixelzoom** [comment]
Carousel uses `clipArea`, and scenery doesn't consider clipArea when it renders pointer areas.  So you're seeing pointer areas for all of the items in the carousel, not just the items that are visible in the carousel's clipArea.

**Comment by pixelzoom** [comment]
Also FYI... We have decided more than once that this is not an issue.  See https://github.com/phetsims/function-builder/issues/81#issuecomment-230060282 and https://github.com/phetsims/function-builder/issues/125#issuecomment-483433394.

**Comment by samreid** [comment]
Thanks @pixelzoom, back to you @KatieWoe.

**Comment by KatieWoe** [comment]
In that case I believe this can be closed
