### ISSUE TITLE
dependency missing in README.md

### ISSUE THREAD

**Issue by lehrer-roller** [phetsims/circuit-construction-kit-dc#189]
Hi,

i cloned the project according to the list of dependencies in README.md, but I found that I also had to clone bamboo:
`git clone https://github.com/phetsims/bamboo.git`

After that, it works on my local machine.

Best,
lehrer-roller

**Comment by samreid** [comment]
Thanks so much @lehrer-roller, bamboo was added in https://github.com/phetsims/circuit-construction-kit-dc/commit/117698418ceca9b18d34a23184e1dd144de65115, closing.
