### ISSUE TITLE
User suggestion: ammeter two probes

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#19]
It looks good, I really like that the resistors change their color code and that the light can change its resistance to zero.
But could the ammeter also have two probes to reinforce that the flow of electrons goes through the meter and that the circuit must be interrupted. I know that newer ammeters do not need to interrupt the circuit but multimeters do have this requirement.
Adding a switch would also be helpful.

**Comment by arouinfar** [comment]
@oliver-phet we will be adding a switch and a more traditional ammeter (that requires inserting the meter in series) to CCK: DC. However, these features are still in the design process.
