### ISSUE TITLE
Why is there a cck:dc /latest/ directory?

### ISSUE THREAD

**Issue by mattpen** [phetsims/circuit-construction-kit-dc#195]
@samreid - There is a static /latest/ directory in cck:dc's deployment directory.  This folder could be causing conflicts with the `/latest/` redirect rule that serves the last deployed version for web requests for that directory.  Can this latest file be removed?

```
[mape5853@phet-server html]$ pwd
/data/web/static/phetsims/sims/html
[mape5853@phet-server html]$ ls -l circuit-construction-kit-dc/latest/
total 3848
-rw-rw-r--. 1 tomcat phet 1550652 Aug 25  2017 circuit-construction-kit-dc_en-dev.5.html
-rw-rw-r--. 1 tomcat phet 1791671 Aug 25  2017 circuit-construction-kit-dc_en.html
```

**Comment by samreid** [comment]
I don't know or recall it, could it be related to prior prototype releases?  As far as I know, it could be removed.  Can you please remove it or reassign to me if I should?

**Comment by mattpen** [comment]
I don't recall any prototype releases from 2017, but I assume it was something like that.  I removed it from phet-server's hard drive.  It can be restored at any time from the peta library if needed.
