### ISSUE TITLE
Electrical current glitch

### ISSUE THREAD

**Issue by AstronautPro** [phetsims/circuit-construction-kit-dc#196]
A friend of mine was on this Phet sim. and accidentally caused the current to glitch. I asked her to try a different iOS update on another device but she could still reproduce it.
![386EBB12-526C-4822-A9D0-C69EC0D24598](https://user-images.githubusercontent.com/100982267/156866985-d3a74478-c9ed-4e70-b523-674dbbef747a.png)

https://user-images.githubusercontent.com/100982267/156866986-f83201bc-f888-4fc1-ba0f-64ae7f21ec3c.MOV

https://user-images.githubusercontent.com/100982267/156866987-abfbb833-c3f2-464d-94cc-aacb16bdb865.MOV

.

**Comment by samreid** [comment]
@arouinfar is this a known problem?

**Comment by matthew-blackman** [comment]
@samreid and I recreated the exact circuit shown above and were not able to reproduce the issue. @samreid mentioned that we now have code to ensure that nothing is happening for an open circuit. We believe this issue is likely resolved and can be closed until further reports come in.
