### ISSUE TITLE
User suggestion: LED

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#20]
> Introduction of a diode (or LED) to the Circuit Construction Kit. My students need to know the IV characteristics curves of ohmic and non ohmic components, specifically a resistor, a filament lamp and a diode. Obviously the resistor and filament lamp are covered but there does not appear to be a diode on the app. This would really help my students.

**Comment by arouinfar** [comment]
@oliver-phet we have been discussing the inclusion of non-Ohmic components in CCK: DC, including the possibility of an LED (diode) and a non-Ohmic bulb (filament lamp).
