### ISSUE TITLE
User suggestion: more components

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#21]
> I am a Professor at Conestoga College in Guelph, Ontario and currently teach Electrical/Electronics in our Truck and Coach programs. I wonder if you can tell me if you are looking at all at the following:
> 
> 1) Meter activities using a DMM
> 2)    Circuit simulations similar to a vehicle electrical system (ie starting circuit, lighting circuits (LED) etc)
> 3)    Adding more components to the simulator such as a fuse(very important) and perhaps a motor(DC,stepper etc) or something that can be customised for larger circuits
> 4)    ​Electronics components to simulate circuits such as 555 timer, regulators, diodes and rectifiers etc.
>

**Comment by arouinfar** [comment]
Thanks @oliver-phet.

> Meter activities using a DMM

I'm not entirely sure what the user means by "meter activities" but I don't believe we have any intention of creating a single multimeter. Instead, we'll have separate meters for voltage and current.

> Circuit simulations similar to a vehicle electrical system (ie starting circuit, lighting circuits (LED) etc)

We will most likely be adding an LED to CCK: DC.

>Adding more components to the simulator such as a fuse(very important) and perhaps a motor(DC,stepper etc) or something that can be customised for larger circuits

I'll look into the possibility of adding a fuse (see #22). I think a motor is likely beyond the ​scope of CCK: DC, but it's something we've discussed including in CCK: Basics.

> Electronics components to simulate circuits such as 555 timer, regulators, diodes and rectifiers etc.

It's unlikely that we'll include <i>all</i> of these components, but we're certainly considering an LED (diode). I'll need to read more about the other components. Self-assigning for further research.

**Comment by ariel-phet** [comment]
I am actually generally a fan of adding a motor (not a stepper motor) since it can likely have a simple model much the light bulb (more current means a faster spin). I feel like it is a component worth of being in both DC and Basics (personally)

Some of these other components (555 timer, regulators, rectifiers, etc) get far beyond the scope of our learning goals.

**Comment by arouinfar** [comment]
@ariel-phet after reading the relevant Unfuddle tickets (I'll get them moved over to GitHub this afternoon) I would agree that a motor would be worth adding to CCK: DC. I wasn't that familiar with the other components the user suggested, but after reading about them a bit more, I would agree that they are beyond the scope of the sim.

I'll be opening separate issues for the diode/LED and motor and pasting in the relevant user requests, but for now I'll leave this issue open.
