### ISSUE TITLE
User reported issue: ammeter

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#24]
> Thank you for the HTML version – however I have a concern about how the ammeter hooks up.  It seems like you just have to put it on the circuit (IE in parallel), not take the circuit and put it as part of the circuit (IE in series).  The Java version does this much better. This will be confusing to the students.
>   I wish you had leads coming from the ammeter just like the voltmeter (and more like an ammeter in real life)

**Comment by arouinfar** [comment]
@oliver-phet the Java version of CCK has two different ammeters: Ammeter & Non-contact ammeter. The "Virtual Lab" flavors of CCK do not include the non-contact ammeter. CCK: Prototype only has the non-contact ammeter, but CCK: DC will include both varieties.

The ammeters typically used in classrooms require the user to break the circuit and insert the ammeter like so:
![image](https://cloud.githubusercontent.com/assets/8419308/23532731/40fa075c-ff6a-11e6-8e21-47171b6cf5d5.png)

The non-contact ammeter can read directly over the wire, and allows for students to take quicker measurements.
![image](https://cloud.githubusercontent.com/assets/8419308/23532754/6a2a533e-ff6a-11e6-8215-c592368774a3.png)

There are real-world, non-contact ammeters (usually called "current clamp" or "clamp-on ammeter"), but they generally look something more like this.
![image](https://cloud.githubusercontent.com/assets/8419308/23532802/c0b41cbc-ff6a-11e6-9a06-9dc25b9f41fc.png).
