### ISSUE TITLE
Add screen icons

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#26]
Now that we decided to have 3 screens, we will need icons for the screens.  @arouinfar can you please recommend or create something for the icons?

**Comment by arouinfar** [comment]
This issue will need to wait until we have the artwork for the grab bag items, but I have a rough idea for the screen icons. 

* Intro: Single light bulb (major goal of this screen is to create a complete circuit/light a light bulb)
* Explore (??): Variety of grab bag items 
* Lab: Variety of circuit components, similar to the current icon. Alternatively, could show circuit components and grab bag items together. For 1.1, show more advanced circuit components like the fuse and LED. 

What do you think @samreid?

**Comment by samreid** [comment]
A lit bulb for the first screen sounds OK for the navbar icon (not sure how it would look as a large homescreen icon though).  Not sure about showing grab bag items or circuit components for screen 2-3 (but don't have any better recommendations at the moment).

**Comment by arouinfar** [comment]
@samreid @ariel-phet I'm definitely open to suggestions, but I don't know if we want to show any complete circuits in the screen icons, as that may give away too much information.

**Comment by ariel-phet** [comment]
@arouinfar @samreid I think in the lab icon it might be good to have some sort of measurement being made, perhaps with the realistic ammeter. Or perhaps just the voltmeter probes across some circuit element.

I agree intro icon should be a lit bulb.

As for explore, maybe show a couple connected items but not a complete circuit, so perhaps wires go "off screen" of the icon and a couple of elements connected to the wires.

**Comment by samreid** [comment]
Reassigned to @arouinfar to review @ariel-phet's recommendations.

**Comment by arouinfar** [comment]
I'm not sure if we want to show a lit light bulb for the Intro screen icon, but if we do, I think we'll want to run wires off-screen like so. I think a having a lit, disconnected bulb would be a bit odd.
<img width="300" src="https://cloud.githubusercontent.com/assets/8419308/25200780/c6fb848a-250c-11e7-9634-7bc02b00021c.png">

For Explore, we could do something like this, but replace the resistor a Grab Bag item, like the coin
<img width="300" alt="screen shot 2017-04-19 at 2 32 56 pm" src="https://cloud.githubusercontent.com/assets/8419308/25200858/1c86cf0e-250d-11e7-8b5b-0cec37f32755.png">

I really like the idea of taking a measurement in the Lab screen icon. I think the electrons may also give it a lab-y feel, but we'll probably need a simpler version for the navbar (maybe just the meter?). 
<img width="300" alt="screen shot 2017-04-19 at 2 31 48 pm" src="https://cloud.githubusercontent.com/assets/8419308/25200856/1b5160ae-250d-11e7-80d2-462a5d53df5f.png">   <img width="300" alt="screen shot 2017-04-19 at 2 34 41 pm" src="https://cloud.githubusercontent.com/assets/8419308/25200917/5a66c324-250d-11e7-8998-d153903f48bc.png">

Once we have the inline ammeter, we could use that instead. 
<img width="300" src="https://cloud.githubusercontent.com/assets/8419308/25201276/5d8683e0-250e-11e7-9f31-d97d7387da27.png">

**Comment by arouinfar** [comment]
Intro: Single bulb, not lit, similar to CL:B
![image](https://cloud.githubusercontent.com/assets/8419308/25252536/9e1b97c0-25da-11e7-9416-ba0dd7e39fb0.png)
Explore: Single grab bag item (coin?) with wires going off screen, electrons on
![image](https://cloud.githubusercontent.com/assets/8419308/25252436/37c54d2c-25da-11e7-9581-8402de8ac1ef.png)
Lab: Act of taking a measurement, don't need the entire voltmeter, probes ok
![image](https://cloud.githubusercontent.com/assets/8419308/25252527/9431fc0e-25da-11e7-9baa-efb856cd29f4.png)

**Comment by samreid** [comment]
For the latter 2, I'm concerned about memory/cpu and debuggabiltiy (now there would be 2 CircuitNodes instead of one) of coding those.  I wonder if we should include them as PNGs generated from AI files.  The LightBulb seems fine to render programmatically as an icon.

**Comment by arouinfar** [comment]
@samreid I would be happy to create .png files for the icons. We'll need the coin artwork before moving on with the Explore screen, though. Let me know what you'd prefer.

**Comment by samreid** [comment]
I already created 2 icons, not sure if they are in a dev version yet

**Comment by samreid** [comment]
Intro and lab icons are visible here and ready for feedback: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.42/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
Coin icon is visible in this dev version:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.63/circuit-construction-kit-dc_en.html

I zoomed in a bit compared to https://github.com/phetsims/circuit-construction-kit-dc/issues/26#issuecomment-295912424 so it is easier to see on both the home screen and navbar.

@arouinfar can you please review the icons?

**Comment by arouinfar** [comment]
Love the screen icons @samreid!!
