### ISSUE TITLE
User suggestion: show currents through circuit elements (not just wires)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#27]
> However when holding the ammeter over the cell no current reading is shown.  This is a source of great confusion to children.  They need to know that the current flowing around the circuit must also flow through the cell.  (Neither is the current reading shown when hovering over the filament of the bulb (this must be a mistake?)).
>  
> In this case the electrons are shown moving from –ve to+ve, and the current reading in the ammeter is always positive even if you rotate the cell.   This means you could arrange for the current reading to show when you hold over the cell just to show that there is a current in it.  (Personally I think the current reading should show +ve or –ve….and would then show a different sign in the cell?  …but it would be difficult to decide how to deal with the probe itself. )
> So how about simply showing the current in the cell and in the filament?

**Comment by arouinfar** [comment]
Another user has requested we add an additional decimal place to the current meter readout.

Unfuddle ticket [#3728](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3728?cycle=true)
> I want to use “Circuit contraction kit AC / DC” as a formal program for the lab But I find two problems before satisfying that
we using a little voltage as 12 v to a void electric shock .. then the current will be in mill amp . The Ammeter is not sufficient sensitive for this, for example the current is 0.012 amp -> 12 m A the ammeter read 0.01 amp .

**Comment by arouinfar** [comment]
If we allow the non-contact ammeter to read over components, as the user in https://github.com/phetsims/circuit-construction-kit-dc/issues/27#issue-211793976 suggested, we may be able to avoid user issues such as https://github.com/phetsims/circuit-construction-kit-dc/issues/37.

**Comment by samreid** [comment]
Are you suggesting the user could read the current through the battery?  Presumably they would see the same problems if they read the current through the resistors.

**Comment by samreid** [comment]
@arouinfar it wouldn't be too much programming work to show current through batteries or resistors.  I am mainly concerned with (a) analogy to real life and (b) consistency within the other tools in the sim.  It seems like the voltmeter should not read out a value if touching the (non-conductive) casing of the battery but what would happen in real life with a non-contact ammeter over a battery?

**Comment by arouinfar** [comment]
> it wouldn't be too much programming work to show current through batteries or resistors

Good to know @samreid!

> (a) analogy to real life 

I think the non-contact ammeter is best represented by an AC/DC current clamp, such as this one:
http://en-us.fluke.com/products/all-accessories/fluke-i1010.html#techspecs

Generally, they're supposed to read over wires, but I don't know if they would also be able to read over a simple resistor or AA battery. @ariel-phet do you know?

> (b) consistency within the other tools in the sim. It seems like the voltmeter should not read out a value if touching the (non-conductive) casing of the battery but what would happen in real life with a non-contact ammeter over a battery?

If a real-life current clamp could read over our batteries and resistors, then I don't see it at all being inconsistent with other tools in sim.

**Comment by ariel-phet** [comment]
@arouinfar I see no reason to not read over a resistor, there is certainly current going through the resistor. Such clamps use measurments of the magnetic field to the best of my knowledge (and quick research) and magnetic fields are *very* difficult to shield, so a normal resistor would not be an issue. I think the main issue is that in the real world such instruments are made to read higher currents, as low currents become difficult to read. However, it seems the pedagogical usefulness of reading currents outweighs us stretching what is normally possible a bit.

**Comment by arouinfar** [comment]
Thanks for your input @ariel-phet! When researching current clamps, I couldn't find one that read DC currents < 1 amp, though I think we are making a reasonable simplification to allow them to read lower currents, given the pedagogical advantages. 

Any thoughts about reading over the batteries? I imagine the battery casing may shield the B-field more than the resistor would, but I wouldn't be overly bothered if we allowed the meter to read over batteries.

**Comment by ariel-phet** [comment]
Totally fine with reading over batteries in my opinion

**Comment by arouinfar** [comment]
@samreid please update the behavior of the non-contact ammeter to read over batteries and resistors.

**Comment by samreid** [comment]
To implement this, it would be great if I could use the same code that scenery uses for pointer hit detection.  @jonathanolson do you know if I can leverage that?  I need to know if a point hits a node.

**Comment by samreid** [comment]
This code is working OK for coordinate transforms and avoiding hitting the probe itself.  However, it is still hitting the vertex circles:

```js
      var x = probeNode.translation;
      var glob = probeNode.parentToGlobalPoint( x );
      var y = this.circuitNode.mainLayer.globalToParentPoint( glob );
      // console.log( position );
      // console.log(position);
      console.log( y );
      var trail = this.circuitNode.mainLayer.trailUnderPoint( y );
      if ( trail ) {
        console.log( trail.lastNode() );
      }
      else {
        console.log( trail );
      }
```

**Comment by samreid** [comment]
I added current readouts over every circuit element type.  Looks good for lifelike mode but not working yet for schematic battery, schematic resistor leads or schematic light bulb.

Here's a dev version with it working for lifelike view: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.30/circuit-construction-kit-dc_en.html

@arouinfar can you review this as far as it goes for lifelike view?  I'll create a separate issue for schematic view.

**Comment by arouinfar** [comment]
Everything looks good in the lifelike view!

**Comment by arouinfar** [comment]
@samreid I just noticed that the probe also reads over the lifelike bulb. I find this a little unrealistic because the filament is encased in glass, but I'm not overly bothered by it.

**Comment by samreid** [comment]
I noticed that too, but I think it is good to be uniform, and I agree with:

> However, it seems the pedagogical usefulness of reading currents outweighs us stretching what is normally possible a bit.

**Comment by arouinfar** [comment]
Agreed @samreid. I'll make a note of it in the Teacher Tips.
