### ISSUE TITLE
User reported issue: extra electron when moving bulb

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#28]
> Usually, when a light bulb is on the screen, there are four little blue electrons displayed on it. However, when two or more light bulbs are on the screen, and either light bulb is dragged around, a fifth electron is displayed at the base of the light bulb. This electron is only visible during the light bulb's movement, and disappears as soon as the light bulb is stationary.

**Comment by phet-steele** [comment]
This would be phetsims/circuit-construction-kit-common/issues/251
