### ISSUE TITLE
User suggestion: additional components

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#3]
I use Phet once in a while in my classroom and I was wondering if there is any way to add more components to the DC circuits. I am in automotive/Truck and Coach and would like different applications such as a fuse or circuit breaker, fans and different types of switches. Is this within the capabilities of the programmers or is this locked down to what we see is what we get?
On the plus side, great simulators for showing basic circuit faults.

**Comment by samreid** [comment]
@arouinfar can you evaluate this recommendation and help Oliver respond to our client?

**Comment by arouinfar** [comment]
@samreid @oliver-phet We haven't discussed such components within the scope of CCK: DC, but we have considered items such as the fan for CCK: Basics. We can keep these suggestions in mind when we continue the design discussions for the CCK suite.

**Comment by arouinfar** [comment]
These requests are being tracked in the issues referenced above. Closing.
