### ISSUE TITLE
Controls for internal resistance of battery

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-dc#36]
In Java, the battery can have an internal resistance of up to 9 ohms. We have not yet discussed this feature, though I imagine it will be desirable for 1.0. Self-assigning to mock up a few options.
<img width="219" alt="screen shot 2017-03-23 at 4 29 14 pm" src="https://cloud.githubusercontent.com/assets/8419308/24273051/e111e7a6-0fe5-11e7-88f9-85818a6abf91.png">    <img width="219" alt="screen shot 2017-03-23 at 4 28 49 pm" src="https://cloud.githubusercontent.com/assets/8419308/24273052/e115862c-0fe5-11e7-9b18-514a7d7130ec.png">

**Comment by arouinfar** [comment]
Add "Battery Internal Resistance" accordion menu to Lab screen like the Wire Resistivity controls. Range 0-10 ohms. Thumb snaps to 1 ohm intervals. Tick marks at each value -- no readout/tweaker necessary. Leaving self-assigned to mock up.

**Comment by arouinfar** [comment]
Initial mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/25026663/bd982166-2064-11e7-82fe-64438869f469.png)

"Battery Internal Resistance" is a bit too verbose, so I went with "Battery Resistance". We can tweak the title later, if need be. I couldn't find an example of a slider that included units on the tick marks, so I added a readout. Still not sure that this needs tweakers, though the readout looks slightly naked without them.

**Comment by samreid** [comment]
@Denz1994 there is no model to hook this up to yet, but can you work on the view?

**Comment by Denz1994** [comment]
I began working on this. The readout still needs to be modified to update in response to the slider value. Also, there also needs to be adjustments to the layout of the panels to allow for the battery resistance panel to fit.

![image](https://cloud.githubusercontent.com/assets/13894380/25109261/c2b6dbba-2398-11e7-8e74-9e3daa1bf8f0.png)

![image](https://cloud.githubusercontent.com/assets/13894380/25109295/efc93148-2398-11e7-9842-730bee1e2e90.png)

**Comment by samreid** [comment]
Thanks @Denz1994!  I realize you aren't done with this issue yet, but I'm going to commit a few minor fixes, some TODO comments and add some review comments here.

**Comment by samreid** [comment]
OK commits are above and review comments are here:

- [ ] BatteryResistanceControl tandem arg is unused
- [ ] Factor out `trackSize: new Dimension2( 150, 5 )` to constants file and share with Resistivity slider
- [ ] See if other constants can be shared with resistivity control
- [ ] `createText` and `createText` should have JSDoc
- [ ] This line:

```js
children: min ? [ createText( '0', true ) ] : [ createText( '10', true ) ]
```
should be simplified, something like this (please check me):
```js
children: [ createText( min ? '0' : '10', true ) ]
```

- [ ] line break is odd in this part:

```js
    var backgroundNode = new Rectangle( 0, 0, 60, 20,
      2, 2, {
```

- [ ] The value display stroke seems too thick
- [ ] Evaluate whether we should be using NumberControl.js (not sure if the arrows can be disabled)
- [ ] This slider code should be closer to the slider creation, if possible:

```js
    slider.addMajorTick( 0, createLabel( true ) );
    slider.addMajorTick( 5 );
    slider.addMajorTick( 10, createLabel( false ) );
    for ( var i = 1; i < 10; i++ ) {
      if ( i !== 5 ) {
        slider.addMinorTick( i );
      }
    }
```
- [ ] The accordionBox should have its fill, corner rounding, layout and other values factored out.

**Comment by samreid** [comment]
Depending on how many things need to get factored out between WireResistivityControl and BatteryResistanceControl, we should consider factoring out a parent class CircuitConstructionKitSliderControl.js which would be the parent class for both WireResistivityControl and BatteryResistanceControl (with option to show/hide the number box).

**Comment by samreid** [comment]
I also created an issue for @arouinfar about dealing with the layout problem @Denz1994 discovered: https://github.com/phetsims/circuit-construction-kit-common/issues/286

**Comment by Denz1994** [comment]
> CircuitConstructionKitSliderControl.js which would be the parent class for both WireResistivityControl and BatteryResistanceControl (with option to show/hide the number box).

I had this in mind when implementing the BatteryResistanceControl. I would imagine it would follow a similar pattern in ```CircuitElementEditContainerPanel.js lines 71-86.

**Comment by Denz1994** [comment]
> Evaluate whether we should be using NumberControl.js (not sure if the arrows can be disabled)

I don't see an option to disable the arrowNodes. What I could do is make their scale really small with ```arrowButtonScale : 0.00000001``` as an option. The scale can't be zero or else an assertion error is fired. Seems a bit hackish though.

**Comment by samreid** [comment]
The existing control seems like it is working well, closing.
