### ISSUE TITLE
User reported issue: resistance of wire

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#38]
> I have been using the Circuit Construction (AC&DC) kit for several years now with great success, but I think I've discovered a bug.
> 
> When the wire resistivity is set to "almost none" my understanding is that it was calculated as actually zero resistance.  In this vain, lengthening or shortening the wires shouldn't affect the current through them.  This is a great way to emphasize the nature of parallel vs series circuits for students, while not focusing on the length of the wires they're using.
> 
> However, this seems to be applied inconsistently when batteries are connected in parallel.   It seems that the wires (or batteries?) are aquiring some internal resistance in this configuration, but not for batteries in series.
> 
> When the length of the wires attached to the batteries is exactly equal, they provide equal currents.  (screenshot 1)
![screenshot1](https://cloud.githubusercontent.com/assets/5090275/24881285/910f9ab4-1dfa-11e7-800a-efa80f1b086d.png)

> 
> However, when the length of these wires is different, the resistance seems to be different, and the current provided by each is shown to be different.  (screenshot 2)
> 
![screenshot2](https://cloud.githubusercontent.com/assets/5090275/24881289/94f35030-1dfa-11e7-9f84-4c4d043f670c.png)

> The strange thing is this ONLY seems to apply to batteries in parallel.  The other part of the circuit feeding the light bulb can be lengthened or shortened (see screenshot 3 below) and it doesn't affect the resistance (and therefore current, 0.9 A) through the bulb.
> 
![screenshot3](https://cloud.githubusercontent.com/assets/5090275/24881297/98472342-1dfa-11e7-8b73-8cb405d7b91e.png)

> I would suggest for the HTML5 version of this sim that you include the ability to set wire resistivity to EXACTLY zero, and display it as such.  I know this will result in infinite current,  but the flaming battery demonstrates this nicely (and my students love it).  It would be great if wire resistivity were applied to all wires in the sim.
> 
> It's possible I'm reading something wrong, but I've restarted the sim and tried it on multiple machines - it seems like the wires attached to batteries somehow create resistance, or maybe they create an internal resistance in the battery which isn't being shown, but is still being used in the calculations?
>

**Comment by arouinfar** [comment]
@oliver-phet the model does not support wires with zero resistance, so we will not be able to address this user's suggestion. Please let me know if you'd like me to draft a response to the user.

**Comment by oliver-phet** [comment]
User email has been forwarded to @arouinfar so that she can respond.
