### ISSUE TITLE
Where is the design doc?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#4]
@arouinfar @ariel-phet @kathy-phet I'm having trouble finding the design doc for the CCK: DC simulation.  I don't recall for certain if we had a design doc, but I recalled seeing mock-ups or having discussion about what would be in the control panels, etc.  Can you help?

**Comment by arouinfar** [comment]
Looks like I didn't get it migrated over to phet-docs. It's there now, and I've given you edit access @samreid. Check your email for the Drive invite.

**Comment by samreid** [comment]
Got it, thanks!
