### ISSUE TITLE
Should we hide the label text when a sensor is out of the toolbox?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#44]
Should we hide the label text when the sensor is out of the toolbox?

![image](https://cloud.githubusercontent.com/assets/679486/26364648/3e2f8ab0-3fa2-11e7-8f56-62b0028a9d6b.png)

That is currently how things work for the circuit element panel.

![image](https://cloud.githubusercontent.com/assets/679486/26364679/576b7b1a-3fa2-11e7-8caa-705bf5125029.png)

**Comment by arouinfar** [comment]
@samreid I don't think we need to worry about hiding the labels when the tool in in the play area.

**Comment by samreid** [comment]
OK, it does leave a nice reminder of what belongs there.
