### ISSUE TITLE
Ammeter probe doesn't work over some schematic elements

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#45]
From #27 

I added current readouts over every circuit element type.  Looks good for lifelike mode but not working yet for schematic battery, schematic resistor leads or schematic light bulb.

**Comment by samreid** [comment]
Proposed fix is in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.31/circuit-construction-kit-dc_en.html

I went with the bounding box for those elements where hit testing wasn't working.  @arouinfar can you see if this is OK?

**Comment by arouinfar** [comment]
@samreid everything is looking good for the schematic items too. 👍
