### ISSUE TITLE
problems with README.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-dc#51]
(1) Currently shows a published README.md, but the sim is not officially published.

(2) assets/*screenshot.png is missing, so it doesn't appear in README.md:

![screenshot_282](https://user-images.githubusercontent.com/3046552/27149658-8ad74a2c-5101-11e7-994e-e53749ffdeb4.png)

(3) Clone commands are wrong, `twixt` is required but missing.

**Comment by samreid** [comment]
Fixed to use unpublished readme in eeac359fd6f63b0b44e0e9bb45604678ca4cf86d, closing.
