### ISSUE TITLE
Namespace casing

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#54]
I noticed the namespace is circuitConstrcutionKitDc instead of circuitConstrcutionKitDC, would that be hard to change?

See https://github.com/phetsims/circuit-construction-kit-dc/issues/53

**Comment by samreid** [comment]
The problem is in checkNamespaces:

![image](https://user-images.githubusercontent.com/679486/27703226-ece0499e-5cc3-11e7-954f-43de99adb02a.png)

Should I roll with Dc or should we figure out a way to make this be DC?

**Comment by pixelzoom** [comment]
phScale vs pHScale is similar.  I rolled with phScale.  Since it's not user-visible, I don't think it's worth the hassle to change.

**Comment by samreid** [comment]
OK thanks, I'll keep it as is, closing.
