### ISSUE TITLE
What should the credits be?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#55]
Discovered in https://github.com/phetsims/circuit-construction-kit-dc/issues/53

We need to figure out exactly who belongs in the credits.

**Comment by samreid** [comment]
@arouinfar can you take the lead on this?

**Comment by arouinfar** [comment]
I reviewed the credits in dev.75, and recommend the following changes:
* Move Denzell Barnett from Team to Software Development
* Add Wendy Adams and Carl Wieman to the Team

@phet-steele will probably need to add a few names to the QA credits, but that should wait until the sim is further down the testing pipeline.

**Comment by samreid** [comment]
I made the changes @arouinfar recommended, reassigning to @phet-steele to find out about the QA team when the time is right.

**Comment by phet-steele** [comment]
QA credits accurate as of 10/6/2017.

**Comment by samreid** [comment]
Thanks, closing for now.  We can reopen if QA team changes.
