### ISSUE TITLE
Publish a prototype containing only the explore screen

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#6]
See https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/29

**Comment by samreid** [comment]
On hold until testing in https://github.com/phetsims/tasks/issues/765 is complete.

**Comment by samreid** [comment]
The phet-io version of CCK has been tested and approved for our collaborators.  Perhaps we could use that as a starting point for publishing the "prototype".

**Comment by samreid** [comment]
On Jan 13, 2017 @kathy-phet said:

> 4 weeks from now might not be useful to them. If testing of Shima's version reveals serious bugs, then this would become more attractive to me. 

EDIT: changed now=>not

Today marks 5 weeks since @kathy-phet said that, so before spending time on this I thought I'd check in with @kathy-phet.  After several RC's we are feeling more comfortable that we have a solid version would probably work for the prototype.  Only brief spot checks would be necessary to make sure a single-screen re-titled version works equally well.

@kathy-phet want to go for it?

**Comment by samreid** [comment]
I also sent an email:

> Kathy,

> I commented in https://github.com/phetsims/circuit-construction-kit-dc/issues/6 but wanted to catch you here on email in case time is critical.  We finished RC testing for the CCK and could use that to publish a first-screen-only non-PhET-iO "prototype".  In your email below you said "4 weeks from now might not be useful to them", and it has been 5 weeks since you said that.  So I wanted to check in and see if we missed the boat or if you would still like to continue with a "prototype" version.

> Best Regards,
Sam

**Comment by samreid** [comment]
On 2/17/17 1:52 PM, Kathy Perkins wrote:
> It's a wide boat, so while we have missed a bit of it we certainly haven't missed the whole range.
>
> If the "prototype" version looks good, then yes, I would definitely be in favor of posting it.
>
> Kathy 

I replied:

> Thanks, I'll look into it.

> Best Regards,
Sam

**Comment by kathy-phet** [comment]
Specifically, here is how wide the boat is -- so a lot of people may still be interested! 

![image](https://cloud.githubusercontent.com/assets/5096804/23082921/af9441de-f518-11e6-8ea2-34fb2de2f082.png)

**Comment by kathy-phet** [comment]
@samreid - Please coordinate with JO on the tracking codes that should be in there.

**Comment by samreid** [comment]
@jonathanolson - Kathy suggested for me to coordinate with you about the tracking codes for a CCK prototype.  Can you help?

**Comment by jonathanolson** [comment]
I'll be available to help (asked some initial questions on Skype).

**Comment by samreid** [comment]
I published a dev version here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.3/circuit-construction-kit-dc_en.html

* I confirmed that the Ammeter is not bounded as requested by @arouinfar in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/29#issuecomment-273262074
* I confirmed the name is "Circuit Construction Kit: Prototype"
* I confirmed the tweakers are at 0.5 as requested in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/29#issuecomment-272558082
* I followed @pixelzoom suggestion to use "dev" identifier

This is using the same branches as the published PhET-iO Black Box Study that got published today.  Would be great to get some spot testing (one platform) to make sure there are no incompatibilities or problems.

**Comment by samreid** [comment]
@phet-steele or @arouinfar are you available for a brief one-platform spot check?

**Comment by samreid** [comment]
@jonathanolson said:

> What do you need to track? See if adding a loadType in our google-analytics.js (phetcommon) be appropriate?

I don’t know anything abut our tracking codes.  It sounds like Kathy wants to use tracking codes on our CCK Prototype we want to publish.

I presume @kathy-phet wants to make sure we are easily able to count the number of times this simulation is launched, even though it won't be a traditional publication that shows up on our website, and may be created with `grunt deploy-dev` or possibly the RC task if necessary.  I do not know if she wants a custom loadType.

**Comment by samreid** [comment]
Do stats get reported for every version (including versions that contain "-dev.X"?   Or only production versions?

**Comment by phet-steele** [comment]
> @phet-steele or @arouinfar are you available for a brief one-platform spot check?

Looked sane on macOS 10.12.3 Chrome.

**Comment by kathy-phet** [comment]
I would like to be able to track the runs in yotta from this -- since it could be significant if our users pick it up -- so I expect just having it send that message to our logs @jonathanolson would be reasonable. Will it do that?

**Comment by kathy-phet** [comment]
For fun I tried it on my iPhone and it works great! Definitely usable, even on the small screen.

**Comment by arouinfar** [comment]
@samreid looks good on macOS 10.12 and latest Firefox. I think Show Electrons should be on by default to be consistent with the Java version.

**Comment by jonathanolson** [comment]
Would this be a long-term thing that needs to be tracked? Will there be different versions? Does anything need to be tracked besides "this was run"?

**Comment by jonathanolson** [comment]
A few scenarios (didn't see responses above):

- Ideally for short-term tracking (that won't need to be integrated into Yotta's code, I could pull the statistics manually), having a separate gif file get requested would make things easy. Could add query parameters on to it.
- For longer-term tracking (or if this type of tracking will be common), it would be helpful to determine what needs to be tracked. Presumably an entry for Google Analytics would be added, and we'd add info onto the messages sent to Yotta.

**Comment by kathy-phet** [comment]
@jonathanolson - Tracking would only need to be until we publish the regular DC version. We would just need the "this was run" tag - summary for each month. 

The idea is to (manually) place this at the URL that the regular DC version will use, so that when we publish the DC version anyone pointing to this sim will have the latest DC version. 

So something like this: 
https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html

**Comment by jonathanolson** [comment]
> Tracking would only need to be until we publish the regular DC version. We would just need the "this was run" tag - summary for each month.

Ok, sounds good. I've added an initial setup. @samreid, we'll want the following code to run in the sim only when you want to track:
```js
document.createElement( 'img' ).src = 'https://phet.colorado.edu/yotta/cck-dc-proto.gif';
```

Would tomorrow (Monday) work to collaborate on this? I'll want to verify that it's showing up in our Apache logs properly.

**Comment by samreid** [comment]
Sure, I'll be available to work on this today.  But I'm curious why you recommended a separate URL instead of just reusing `https://phet.colorado.edu/yotta/immediate.gif?` together with the URL and version number.  Oh, perhaps if we make a maintenance release, we still want the counting to be easy?

What about allowing simulations to augment `pingParams`?  Would that make things easier?  I'm not opposed to the solution you suggested, but not certain it is the most general in the long term nor that it will integrate seamlessly into the current analysis techniques.

**Comment by jonathanolson** [comment]
@samreid is correct, just filtering the usual Yotta messages should be sufficient in this case (as we can check for specific dev versions, e.g. 1.0.0-dev.3).

I tested by putting http://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html up (1.0.0-dev.3) and verifying that the log entries were present in the Apache logs (includes version number, timestamp as part of the log line, etc.)

This should be more than sufficient for this case, so no new sim code should be required.

**Comment by kathy-phet** [comment]
Great. @samreid - Can you confirm that this is indeed the exact URL (sim name / format) you would expect for once we publish the CCK DC replacement sim? I don't want to have the directory name wrong or anything.

**Comment by kathy-phet** [comment]
@samreid - So it looks like the only other change needed is having electrons on by default? Then this is ready - it seems!

**Comment by samreid** [comment]
The URL http://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html is correct as long as we stick with the name "circuit-construction-kit-dc", though I suppose we would normally go with "https" when sharing it.  I'll turn on the electrons and publish a new dev version.

**Comment by samreid** [comment]
I published a new version at http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.4/circuit-construction-kit-dc_en.html and confirmed that the only differences in the builds are the timestamps, version numbers and having the electrons on by default.

@jonathanolson can you please copy this to the appropriate place on phet-server?  (overwrite the one you created this morning)

**Comment by samreid** [comment]
@jonathanolson overwrote the URL with dev.4.

@kathy-phet it is ready to go.  Please review the concerns raised by @ariel-phet @arouinfar and myself in the "Re: Interim CCK" email thread, as it may help you frame/describe the prototype to our clients appropriately.

**Comment by samreid** [comment]
@kathy-phet said:

> Can you also deploy a new CCK Prototype with the same fixes?

**Comment by samreid** [comment]
I took the SHAs from the tested black-box-study version, updated the version to dev.5 in DC, spot tested light bulbs in one browser and deployed dev.5 as a new dev version.

@jonathanolson can you please overwrite the URL with dev.5?  Also, please post instructions or a script somewhere (possibly not here in a public issue) so that others may easily do this in the future.

**Comment by samreid** [comment]
Working with @jonathanolson we developed this script (replace with whatever version number you want).

cd /data/web/static/phetsims/sims/html/circuit-construction-kit-dc/latest
rm circuit-construction-kit-dc_en.html
wget http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.5/circuit-construction-kit-dc_en.html

Then test by launching http://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
I emailed @kathy-phet the new link.  @kathy-phet can you test it and let me know if this issue can be closed?

**Comment by kathy-phet** [comment]
Tested. Looks great! Thx

Sent from my iPhone

On Feb 28, 2017, at 9:54 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


I emailed @kathy-phet<https://github.com/kathy-phet> the new link. @kathy-phet<https://github.com/kathy-phet> can you test it and let me know if this issue can be closed?

**Comment by pixelzoom** [comment]
This sim has a title of "Circuit Constructor Kit: Prototype", but no corresponding circuit-construction-kit-prototype repository.  This breaks with PhET naming conventions and processes, and (as demonstrated by the confusion on Skype today) is confusing.  It's really great that you could turn this around so quickly. And really not great that you short-cutted PhET conventions and processes in doing so.  Cost me about 30 minutes of time trying to figure it out during publishing a sim, then another 10 minutes having to read this issue.

**Comment by pixelzoom** [comment]
>  Wouldn't it be confusing that the "prototype" repo sim publishes to the "dc" directory?

Yes. Because that also violates PhET convention.

**Comment by samreid** [comment]
Labeled for developer meeting to see if we should take any action or just to wait until 1.0 comes out and see if that resolves it.

**Comment by samreid** [comment]
@ariel-phet recommends no action to be taken at the moment, we had to make prototype to show progress.
