### ISSUE TITLE
Will the carousel be obvious to users?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#61]
Will the carousel be obvious to users?  If you change between blank screen 1 and blank screen 2 it is obvious, but if you create an elaborate circuit on screen 1 then change to screen 2 it could be easy to miss.  Noted during testing in #47

**Comment by arouinfar** [comment]
@samreid I don't see why the carousel wouldn't be obvious to the users, as they've worked well in other sims. I'll be scheduling some interviews for next week, so I can keep an eye out for any usability issues.

**Comment by samreid** [comment]
My hope is that the carousel will be obvious, but I wanted to point out some significant differences between how I've seen carousels used in other sims and how they are used in CCK which raise some concern.  I'll use Function Builder as an example for contrast:

Function Builder screen 1 has a carousel.  Circuit Construction Kit screen 1 has no carousel.  When changing from screen 1 to screen 2 in Function Builder all of the page 1 carousel items change.  In Circuit Construction Kit when you switch from screen 1 to screen 2 *none of the carousel items change* but what actually changes is that the panel changes to a carousel.

**Comment by arouinfar** [comment]
You make some very good points @samreid. Since the circuit component panel will be so heavily used, my feeling is that the panel > carousel change will be more noticeable than if it was a change to some lesser-used panel. But I'll definitely be keeping your concerns in mind when we interview students.

**Comment by ariel-phet** [comment]
@samreid @arouinfar one thought I had was considering a carousel on screen 1, that way the user expectation is already set. For instance, I don't think there would be major harm in putting the high voltage/high resistance items on the intro.

Another possibility to consider, which might simplify the sim a little would be to just take it to 2 screens. Intro and Lab.

On intro you get a carousel with the intro items and the high voltage items. On lab you get those items plus the grab bag items. Really all we are adding on the "Explore screen is grab bag items, so maybe it is not necessary to have that screen.

**Comment by samreid** [comment]
Explore screen is gone and all screens now feature a carousel.
