### ISSUE TITLE
Voltmeter probes do not read switches

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#63]
A closed switch looks like a wire but probes do not read it like a wire, discovered during testing in #47

**Comment by samreid** [comment]
Tagging @arouinfar so she is aware of this issue.

![image](https://user-images.githubusercontent.com/679486/27796817-977095a6-5fc8-11e7-882e-52e95c0a5bff.png)

It would be good to discuss.  Ideally it seems like both the open and closed switch should support voltmeter readings.  It seems like the switch supports ammeter readings already.

I thought I'd ask how important this will be and if it is essential for 1.0 in case it gets complicated.

**Comment by arouinfar** [comment]
> Ideally it seems like both the open and closed switch should support voltmeter readings.

Agreed @samreid. If not prohibitively complicated, it would be nice to support voltmeter readings. Let's discuss at design meeting this week.

**Comment by samreid** [comment]
> I thought I'd ask how important this will be and if it is essential for 1.0 in case it gets complicated.

We decided this is important to investigate.

**Comment by samreid** [comment]
I think this issue is predominantly about the voltmeter probes--it seems the noncontact ammeter already reads values over the switch.

**Comment by samreid** [comment]
Things are kind of working after the changes above.  But now there's a problem reading a voltage drop across a single wire.

**Comment by samreid** [comment]
OK that should be fixed too, ready for testing in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.81/circuit-construction-kit-dc_en.html

**Comment by samreid** [comment]
By the way, big thanks to @jonathanolson for helping with this issue!

**Comment by arouinfar** [comment]
👍
