### ISSUE TITLE
Should pointer area be larger for schematic wire?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#65]
Or possibly for lifelike wires too?  It has swipe to snag but I'm not sure if that's sufficient.  The black wires are pretty thin.  Changing their touch area dynamically while dragging could hamper performance on iPad2.  If we do decide to change it, perhaps just when it stops dragging?

Discovered during #47

**Comment by arouinfar** [comment]
@samreid could you add a little padding to the pointer area for the wire? The same area could apply to the schematic view as well.
<img width="168" alt="screen shot 2017-07-03 at 12 13 06 pm" src="https://user-images.githubusercontent.com/8419308/27803910-31e90526-5fe9-11e7-8242-803feaacbc05.png">

**Comment by samreid** [comment]
I noticed in @arouinfar's mock-up that the pointer area for the wire is shortened so it doesn't overlap with the vertex nodes.  Our policy from the code review is for the pointer areas to not overlap but I'm wondering if that is not a problem as long as we have the z-order correct?  For instance, it may be easier to set the touch area of the wire to go from end to end but have it behind the vertex nodes areas.  @jonathanolson can you comment on z-ordering of touch areas and overlapping?

**Comment by jonathanolson** [comment]
> that is not a problem as long as we have the z-order correct?

I personally believe that's correct (that it has an implicit assumption that things shouldn't overlap in the "same" layer).

**Comment by arouinfar** [comment]
@samreid, I wasn't sure if the vertices were part of the current pointer area (nothing showed up when using ?showPointerAreas) so I left them out. If they should be included, that's fine with me. My only concern is the height.

**Comment by samreid** [comment]
OK I expanded the touch area.  I was concerned about performance but dragging or stretching wires on iPad doesn't seem a lot worse:

![image](https://user-images.githubusercontent.com/679486/28335001-25d79afe-6bba-11e7-97f4-59e516678226.png)

**Comment by samreid** [comment]
Dev version is published here, @arouinfar can you please take a look?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.82/circuit-construction-kit-dc_en.html?showPointerAreas

**Comment by arouinfar** [comment]
Feels good on an iPad @samreid!
