### ISSUE TITLE
It is possible to make overlapping circuits

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#66]
Drag out 2 batteries and connect them.  Then make a wire the length of 2 batteries and drag it across the batteries. Voila!

![image](https://user-images.githubusercontent.com/679486/27796531-8ed59334-5fc7-11e7-960b-1cf418f6ab28.png)

Shall we try to avoid this?  If so, how should it be avoided and what rules determine when to apply the new avoidance strategy?

Discovered in #47

**Comment by arouinfar** [comment]
@samreid can the overlap avoidance code be extended to apply to any number of fixed-length components? For example, connect several fixed-length components together in a line. Attach a wire across the components, upon release the wire will rotate away, as it does in the case of a single battery + wire.

![image](https://user-images.githubusercontent.com/8419308/27804505-7eabc846-5fec-11e7-942e-7c4cb8a343b0.png)
<img width="541" alt="screen shot 2017-07-03 at 12 38 32 pm" src="https://user-images.githubusercontent.com/8419308/27804526-9de7717e-5fec-11e7-9319-b798c7def5ee.png">
![image](https://user-images.githubusercontent.com/8419308/27804523-9577a2d4-5fec-11e7-9292-d754351e1615.png)

**Comment by samreid** [comment]
Sure, we can generalize it to any number of intervening components. Should it have a tolerance limit in case some of the components are slightly rotated?  Or only apply when all components are at exactly 0.000 degrees?

**Comment by arouinfar** [comment]
@samreid the case I'm most worried about would be exactly 0.000 degrees. If the algorithm is already generalized to include an angle, then I can recommend something else. Otherwise, I think addressing to 0.000 degree case is sufficient.

**Comment by samreid** [comment]
It looks like the problem is that the connectivity rule allowed the vertices to connect--the bump away logic is ineffective after the connection is made.  There is a connectivity rule that prevents overlapping a single circuit element.  We may need a connectivity rule that prevents overlapping several circuit elements.

**Comment by samreid** [comment]
I tried this rule but it was pretty jittery:

```js
      // (5.1) Reject any matches that cause vertices to have the same y value--could indicate an overlap
      candidateVertices = candidateVertices.filter( function( candidateVertex ) {

        // if something else is already snapping to candidateVertex, then we cannot snap to it as well.
        // check the neighbor vertices
        for ( var i = 0; i < self.vertices.length; i++ ) {
          var circuitVertex = self.vertices.get( i );
          var adjacent = self.isVertexAdjacent( circuitVertex, vertex );

          // If the adjacent vertex has the same position as the candidate vertex, that means it is already "snapped"
          // there and hence another vertex should not snap there at the same time.
          if ( adjacent && Math.abs(circuitVertex.positionProperty.get().y - candidateVertex.positionProperty.get().y)<10 ) {
            return false;
          }
        }
        return true;
      } );
      if ( candidateVertices.length === 0 ) {return null;}
```

**Comment by samreid** [comment]
It may be easier to add a postprocessing rule rather than an avoidance rule.

**Comment by samreid** [comment]
I haven't found a straightforward solution to this yet--I've marked it for design meeting to discuss implementation strategies.

**Comment by samreid** [comment]
At today's meeting we decided this issue was not worth the trouble and decided to close it.
