### ISSUE TITLE
Add a ?virtualLab query parameter 

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#72]
It will hide the noncontact ammeter and start up with "lab" screen only

**Comment by samreid** [comment]
My gut tells me that it will be easiest if we manage this as the same deliverable with a query parameter.

An alternative would be to create a new repo and new "sim". 

Questions:
1. How do we want to track analytics?  Is it important whether they are different sims?  Or is it OK to track this with query parameters?
2. Will they have different titles?
3. Will we ever want to deploy one without the other?
4. Will we save time on testing by having them "bundled"?  Or will we forget to test ?virtualLab query parameter sometimes and end up deploying broken things?

This seems like a good question for @ariel-phet and @pixelzoom.  If we cannot decide here in the issue we can discuss at developer meeting.

**Comment by pixelzoom** [comment]
Not enough information here. What are the requirements?  Will this be presented on the website as a different sim?

**Comment by pixelzoom** [comment]
If it's presented as a different sim, I'd make a new repo.  Yes, a new repo seems kind of "heavy" for the difference you've described.   But the query parameter solution is a mismatch with PhET processes, resulting in the kinds of issues/questions (and there are undoubtedly others) that you've enumerated. 

My question would be -- why is this even necessary?

**Comment by pixelzoom** [comment]
Is this intended to be similar to this Java "flavor" of CCK?
https://phet.colorado.edu/en/simulation/circuit-construction-kit-dc-virtual-lab

**Comment by pixelzoom** [comment]
If so....

• circuit-construction-kit-dc-virtual-lab repo
• circuit-construction-kit-dc-virtual-lab-main.js which instantiates only `LabScreen`
• hide noncontact ammeter via an option to `LabScreen`

**Comment by samreid** [comment]
Yes, it's an analog for the Java Virtual Lab flavor.  The requirements I am aware of are:
1. it should launch the "Lab screen" only
2. it should hide the non-contact ammeter

I strongly suspect:
1. It will need its own title
2. It will need its own analytics

All of those can be done in 1 repo with "hacks" (a few lines of code).  But I would like a solution that is best in the long run.

**Comment by pixelzoom** [comment]
Concentration and "pH Scale: Basics" are very similar to what you're trying to do here -- cherry pick one screen, with some customization.  The associated repos have nothing but main.js and config.js.  I don't see anything wrong with that approach for the longterm.

**Comment by samreid** [comment]
So is this mainly a question of whether the sim gets its own "sim page"?  For instance, if it is just a link on the "Circuit Construction Kit: DC" would you still recommend its own repo?

Conversely, if the "thin repo" is an established and recommended pattern, should we use that to advocate for a standalone sim page (so this is not a special case)?

**Comment by pixelzoom** [comment]
Even if it has a link on the "Circuit Construction Kit: DC" page, I would highly recommend making ""Circuit Construction Kit: Virtual Lab" also have its own page.   That will have numerous advantages, including:

• Provide a place for teachers to put lesson plans specific to CCK:VL
• Provide a place to access translations
• Fit with PhET test/build/deploy processes

Without a page of its own, we're in new territory -- and (imo) for no good reason.

**Comment by pixelzoom** [comment]
Also note that there's a legacy version:
https://phet.colorado.edu/en/simulation/circuit-construction-kit-dc-virtual-lab

If there's no sim page for the HTML5 version, how do you propose to make the legacy version accessible.

I also see 2 "virtual lab" flavors in Java:
Circuit Construction Kit (DC Only), Virtual Lab
Circuit Construction Kit (AC+DC), Virtual Lab

If the plan is to have HTML5 versions of these, then I recommend that they both follow the "thin sim" implementation pattern (with their own repos) and that they both have web pages.

**Comment by kathy-phet** [comment]
My understanding from the conversation last Thursday was that we were planning to keep the individual sim pages for each current flavor of CCK. Kathy

**Comment by samreid** [comment]
Thanks @kathy-phet and @pixelzoom for discussing this.  So it seems we should remove the `?virtualLab` query parameter and move to a "circuit-construction-kit-virtual-lab" repo solution.

@kathy-phet and @arouinfar does this need to be done for 1.0?

**Comment by pixelzoom** [comment]
@kathy-phet said:
> My understanding from the conversation last Thursday was that we were planning to keep the individual sim pages for each current flavor of CCK.

@samreid 
> move to a "circuit-construction-kit-virtual-lab" repo solution

If what @kathy-phet said is correct, then you need 2 repos:

circuit-construction-kit-dc-virtual-lab
circuit-construction-kit-ac-dc-virtual-lab

**Comment by samreid** [comment]
I'm picturing these repos:

circuit-construction-kit-common
circuit-construction-kit-dc
circuit-construction-kit-dc-virtual-lab
circuit-construction-kit-ac
circuit-construction-kit-ac-virtual-lab
circuit-construction-kit-basics
circuit-builder (iPad app)

I'm not sure if there will be another flavor for the energy circuit sim, or if that will be done in the "basics" repo.

**Comment by ariel-phet** [comment]
@samreid yes, the virtual-lab needs to be done for 1.0

**Comment by arouinfar** [comment]
@kathy-phet I think the goal of ?virtualLab was to avoid giving the virtual lab flavors of CCK their own sim page. However, @pixelzoom has provided several compelling reasons why we should proceed through the standard repo + sim page route for the virtual flavors.

@samreid I would also picture those repos, but we'll need to find an alternative name for the app. There's already a Circuit Builder app on the App Store and Google Play. 

I agree with @ariel-phet that we'd need virtual-lab for 1.0, given that such a large percentage of CCK runs are the virtual lab flavors.

**Comment by samreid** [comment]
I created a new repo and sim that launches the lab screen.  I'll need to add an option that limits to inline ammeters, but that will be in another repo.
