### ISSUE TITLE
Change battery and resistor max to 150

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#73]
So it will cover the 120V range.  We will need to increase the fire current to compensate (so it starts fire at about the same point on the range).

**Comment by samreid** [comment]
Proposed implementation is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.79/circuit-construction-kit-dc_en.html

@arouinfar can you please test?

**Comment by arouinfar** [comment]
👍

**Comment by arouinfar** [comment]
While reviewing dev.80 for #76, I noticed two issues while using a standard 10 ohm bulb and a single battery:
* Animation speed will be reduced around 106 V, but no fire appears
* The 2000 W brightness ceiling will be hit around 142 V

I find the first issue to be a bit problematic. I really like the connection between the reduced animation speed and the appearance of the fire. 

We originally decided to increase the max values to 150V/150 ohms to better accommodate learning goals around household wiring. However, I'm now wondering if it's necessary to reach 120 V using a single battery. Couldn't that goal be achieved by connecting two batteries in series? Reopening for discussion at a future design meeting.

**Comment by samreid** [comment]
I'm also fine with requiring 2x batteries to reach 120V.  I think we discussed it and decided against it, but I can't recall why (nor am I certain that we discussed it).

**Comment by samreid** [comment]
From today's meeting:

change max to 120V.  Make sure no animation speed issue for battery (max) + default bulb.
change max resistance to 120

**Comment by samreid** [comment]
Commit pushed above and ready for testing in this version:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.89/circuit-construction-kit-dc_en.html

@arouinfar and/or @ariel-phet can you please take a look?

**Comment by ariel-phet** [comment]
This looks quite good to me. At default the speed is totally reasonable,  At 0.5 volts with the default bulb the speed is slow but perceptible, and at 120 V the speed is quite fast, but not stroboscopic or such. Seems like a good compromise.

**Comment by arouinfar** [comment]
This is a huge improvement @samreid! The electron speeds at the extreme ends looks good, and the fire and animation speed warning are much better coordinated. Closing.
