### ISSUE TITLE
Wire tips have a crease

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#78]
Perhaps this was introduced when spritesheet padding was added?  Discovered in #76 

![image](https://user-images.githubusercontent.com/679486/28292364-e353a442-6b0b-11e7-94f4-61b4debaa123.png)

**Comment by phet-steele** [comment]
@samreid was introduced earlier in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.74/circuit-construction-kit-dc_en.html

**Comment by phet-steele** [comment]
The wire and the little "dot" for the end of the wire are technically two different images in the spritesheet, no? Maybe you are just seeing two images not mesh well together.

**Comment by samreid** [comment]
Yes, I had to split it into several items to render it with WebGL.

**Comment by samreid** [comment]
There is some bleeding past the edge when I turn the rounded caps off--this could be causing the graying...?
![image](https://user-images.githubusercontent.com/679486/28352498-fe94b0da-6c13-11e7-9632-b3af56a26578.png)

**Comment by samreid** [comment]
I will be somewhat surprised if we need to tile multiple images for the central, stretchy part of the wire.

**Comment by samreid** [comment]
This problem is not quite as bad if we put the caps in front, and doesn't exaggerate as the wire stretches out.

![image](https://user-images.githubusercontent.com/679486/28373336-4d61ddb4-6c5f-11e7-9f78-bf5861ede82b.png)

**Comment by samreid** [comment]
I could also tile other nodes across that buggy patch, but that would add 2 more nodes per wire.  We previously tried to reduce the number of nodes to help with memory and crashing issues.

The commit above was published here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.84/circuit-construction-kit-dc_en.html

@arouinfar is this good enough?  If not, @jonathanolson can you help investigate this problem?

**Comment by arouinfar** [comment]
@samreid I think the solution used in dev.84 is a reasonable compromise. It's definitely an improvement, so I don't think it's worth adding more nodes at the expense of performance.

**Comment by jonathanolson** [comment]
toDataURLImageSynchronous adds padding so that the edges of the "node" getting imaged are included in the image. It's probably antialiased. Then when you stretch it out, the antialiased part gets stretched.

You want to specify custom bounds to the toImage* equivalent so it doesn't include the ends, and doesn't have antialiasing on the ends.

**Comment by arouinfar** [comment]
Thanks @jonathanolson!

> You want to specify custom bounds to the toImage* equivalent so it doesn't include the ends, and doesn't have antialiasing on the ends

@samreid this sounds like you don't need to add more nodes to address the problem, can you investigate?

**Comment by samreid** [comment]
The problem reduces somewhat if I change the padding from 2 to 0:

![image](https://user-images.githubusercontent.com/679486/28396621-df17fe5a-6cb9-11e7-837a-b100fb41d3ef.png)

**Comment by samreid** [comment]
Even with the padding at -2, I am still seeing this problem to some extent:

![image](https://user-images.githubusercontent.com/679486/28396641-fa8d7e08-6cb9-11e7-930b-adc973b8d6ad.png)

**Comment by samreid** [comment]
@jonathanolson am I barking up the right tree?

**Comment by samreid** [comment]
I think it's a WebGL artifact because here is how ?webgl=false renders the padding=0 case:

![image](https://user-images.githubusercontent.com/679486/28397037-4b47ccb6-6cbc-11e7-9b0a-ef9769b2dc93.png)

**Comment by samreid** [comment]
I'm seeing the same blurring on Firefox

**Comment by jonathanolson** [comment]
I'll be handling this in https://github.com/phetsims/scenery/issues/637 (reopened).

**Comment by jonathanolson** [comment]
I believe this is handled. Appearance with and without the cap (on a wire across the whole screen):

![cck-artifact-1](https://user-images.githubusercontent.com/480878/28399307-9d68aa26-6cc9-11e7-9616-708bae7ba26a.PNG)
![cck-artifact-2](https://user-images.githubusercontent.com/480878/28399313-a0bd9c18-6cc9-11e7-979a-8295cac6f98b.PNG)

@samreid can you confirm?

**Comment by samreid** [comment]
Looks great on my side.  However, it was unclear to me why these changes were necessary:

```js
  var lifelikeNodeNormal = new Line( 0, 0, WIRE_RASTER_LENGTH, 0, {
    lineWidth: LIFELIKE_LINE_WIDTH,
    stroke: normalGradient
  } ).toDataURLImageSynchronous( 0, LIFELIKE_LINE_WIDTH / 2, WIRE_RASTER_LENGTH, LIFELIKE_LINE_WIDTH );

  var lifelikeNodeReversed = new Line( 0, 0, WIRE_RASTER_LENGTH, 0, {
    lineWidth: LIFELIKE_LINE_WIDTH,
    stroke: reverseGradient
  } ).toDataURLImageSynchronous( 0, LIFELIKE_LINE_WIDTH / 2, WIRE_RASTER_LENGTH, LIFELIKE_LINE_WIDTH );
```

Can you help me understand when it will be necessary to specify arguments for these and when it won't be?  Is it when a large scaling is applied to a node?  Or a scaling that doesn't preserve aspect ratio?

**Comment by jonathanolson** [comment]
> Can you help me understand when it will be necessary to specify arguments for these and when it won't be? Is it when a large scaling is applied to a node? Or a scaling that doesn't preserve aspect ratio?

As a general rule, it's doing what is usually desired: if an image with a transparent-to-non-transparent pixel edge exists, and you scale it up so each image-pixel takes up 50 real pixels, it's going to interpolate so that you don't see individual blocky pixels. We generally don't want a pixelated look for scaled-up images.

In this case, that's undesirable since you want the full-alpha content to go to the edge, so to*Image's default padding is actively unhelpful. What is happening is that the scaling is taking a 100-pixel image and expanding it to ~2000 pixels, so there is a blur of ~20 pixels where there is interpolation. Removing that padding by specifying a different rectangle makes it so our generated image has no transparent pixels. Since the border of images is sharply cut off, this generates the desired look.

**Comment by arouinfar** [comment]
I took a look at master, and the updated wire tips look amazing!

**Comment by samreid** [comment]
@jonathanolson thanks for explaining that, and for your help.  Closing.

**Comment by phet-steele** [comment]
@jonathanolson @samreid, schematic mode has a blur. Need changing?

![image](https://user-images.githubusercontent.com/5863899/28445205-2f25ec60-6d80-11e7-8521-4ad3f421a80a.png)



Seen in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html on Win 10 Chrome. For phetsims/QA#26.

**Comment by ariel-phet** [comment]
That looks exceedingly minor to me for the moment

**Comment by samreid** [comment]
Proposed fix committed above and published for dev testing here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.88/circuit-construction-kit-dc_en.html

![image](https://user-images.githubusercontent.com/679486/28448469-8e6f48aa-6d95-11e7-9dde-113a57ff10ec.png)

**Comment by phet-steele** [comment]
Looks great, except for phetsims/scenery/issues/652. That issue is tracked separately and is unlikely to cause problems in this sim. Thanks @samreid!
