### ISSUE TITLE
Schematic mode uses incorrect sensor hit areas

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#79]
Discovered in #76, the schematic mode sensor reading areas are the same as the lifelike views:

![image](https://user-images.githubusercontent.com/679486/28292496-73ffdb78-6b0c-11e7-8425-8b25ff823b9c.png)

@arouinfar is this as desired, or should we revise it to use different hit areas for schematic?

**Comment by arouinfar** [comment]
@samreid for usability, I think we want to use the same reading areas for the lifelike view. It may be a bit tricky to place the probe directly over the thinner components, particularly on touch.

**Comment by samreid** [comment]
Sounds reasonable to me, I'll close this as "will not fix".
