### ISSUE TITLE
Current meter should display a precise value when shorted

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-dc#8]
For https://github.com/phetsims/tasks/issues/765.

The modification made to the current meter in https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/6 should not be included in the prototype. Instead, the behavior should be consistent with the Java implementation. That is, large currents are displayed as is. No need to display ">10^4" or similar.

**Comment by samreid** [comment]
We should also make this change for master, right?

**Comment by arouinfar** [comment]
Yes, @samreid. The modification to the current meter should only exist in the branch for Shima's study.

**Comment by samreid** [comment]
Note to self: a better way to manage this would be with a parameter rather than a hard-coded values in branches.

**Comment by samreid** [comment]
Fixed (commit will appear when GitHub processes it).
