### ISSUE TITLE
Cut button doesn't cut wires.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#80]
After about 3 minutes of usage on the iPad2, the wire cut button was unresponsive.  It would press in but not cut the wires.  Discovered in https://github.com/phetsims/circuit-construction-kit-dc/issues/62#issuecomment-315928278 and pertinent to #76

**Comment by arouinfar** [comment]
@samreid I observed this during an interview with dev.79 using Mac/Chrome. I haven't been able to reproduce it myself, though.

**Comment by samreid** [comment]
@arouinfar was this related to the "carousel becomes unresponsive error"?

**Comment by arouinfar** [comment]
@samreid I don't think so. When the cut button broke, I asked the student to test the carousel, and it was still working. The carousel issue is more pervasive. All three students ran into the carousel issue at least twice during their interviews.

**Comment by samreid** [comment]
I haven't been able to reproduce this problem, perhaps I should schedule it for QA testing.

**Comment by phet-steele** [comment]
@samreid, the cut button will never work on the second screen a user visits, assuming the user had dragged out a component on the first screen they visited.

1. On startup, pick a screen and go to it.
2. Drag a component, any component, into the play area. 
3. Switch screens
4. Drag out two components and connect them.
5. Attempt to cut them apart (can't)

Verified in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.86/circuit-construction-kit-dc_en.html on macOS 10.12.5 Chrome. There is NO associated error in the console (when performing this on master).

**Comment by samreid** [comment]
Excellent work @phet-steele!  You are making this too easy!

**Comment by samreid** [comment]
We would like to try to solve this before giving @kathy-phet a version for AAPT.

**Comment by samreid** [comment]
Proposed fix is in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html

**Comment by phet-steele** [comment]
There is an interesting consequence I see from this fix (or maybe it originated elsewhere).

Steps:

1. On the first screen, connect two components
2. On the second screen, drag out one component
3. Back on the first screen, click on the vertex that is the connection. This will bring up an enabled cut button. DON'T press it!
4. Switch back to the second screen
5. Click on a vertex. The cut button is supposed to be entirely gray like this:
![image](https://user-images.githubusercontent.com/5863899/28443780-9621fba8-6d75-11e7-8087-e83953b6c9e2.png)

but instead looks buggy like this, with a dark image + gray fill:
![image](https://user-images.githubusercontent.com/5863899/28443796-ad58acd6-6d75-11e7-88c9-5f625cda3cbc.png)

This procedure works in reverse, too (I think). I once saw a grayed image + yellow fill but I don't know how.

**Comment by samreid** [comment]
Proposed fix pushed above and published here for testing:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.90/circuit-construction-kit-dc_en.html

@phet-steele can you please take a look?

**Comment by phet-steele** [comment]
Good, thanks.
