### ISSUE TITLE
Improvements to pointerAreas in carousel 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-dc#82]
Discovered while playing with http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.80/circuit-construction-kit-dc_en.htm

When trying to push the lower carousel button, several times I grabbed the switch

Looking at `?showPointerAreas`, it appears there are a few usability issues:

1. The padding on all components should be reduced below the label (for instance, there is lots of pointerArea padding below the word Switch that seems unnecessary and problematic). 

2. If possible the carousel "rotating" buttons should have a slightly enlarged pointer area (the top one going a bit above the button, the bottom one going a bit below the button). 

3. Touch areas for items should not overlap (going through the carousel, several do).

![carousel](https://user-images.githubusercontent.com/4051174/28298014-29f4f410-6b2e-11e7-9776-a553a5adb5d2.PNG)

**Comment by samreid** [comment]
Fixed in the above commits, will be ready for testing in next version.

**Comment by samreid** [comment]
Posted for testing in this version: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.85/circuit-construction-kit-dc_en.html?showPointerAreas

Note I have already applied the ?showPointerAreas query parameter.  Here is page 1:
![image](https://user-images.githubusercontent.com/679486/28396417-84d40ae8-6cb8-11e7-9583-821e7bcc5a89.png)

Here is page 2:
![image](https://user-images.githubusercontent.com/679486/28396422-8e15a850-6cb8-11e7-8c50-43037410e363.png)

@ariel-phet can you please test?

**Comment by ariel-phet** [comment]
@samreid pointer areas now look and feel good, and carousel working nicely!

It would also be good to "visually" distribute the items evenly. For instance, there is quite a bit of negative space between the wire and the battery and the resistor and the switch (as examples). I think it would be good to just go through the carousels and "eyeball" and reasonably even distribution between the items. This request is definitely a pixel polish, so feel free to close this issue and make a separate low priority issue. Your choice.
