### ISSUE TITLE
Truncate decimal places for high voltage/high resistance components?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#86]
In #64 @Denz1994 said:

I am wondering if we should treat high voltage components and resistors the same way? There is a  minor overlap that doesn't affect readability, but we do have an added decimal place that is never changed in the sim. It may give us less clutter to remove it.  I don't know if it is pedagogically useful to have the decimal places on these components. Thoughts @samreid?

![image](https://user-images.githubusercontent.com/13894380/28327500-d9e6ee7e-6ba0-11e7-8f4b-28f89e357625.png)

**Comment by samreid** [comment]
Same question for the editor--for these components it doesn't appear possible to go to 0.5, so we may be able to truncate it as well: 
![image](https://user-images.githubusercontent.com/679486/28333846-74b52a00-6bb6-11e7-97e9-c2209d870f3c.png)

**Comment by samreid** [comment]
@arouinfar I'm not sure whether it is better to truncate these since they can be long, or to keep it consistent with the lower resistance components.  What do you recommend?

**Comment by arouinfar** [comment]
@samreid I think it'd be fine to remove the ".0" from the high voltage/resistance components, as that level of precision isn't necessary.

**Comment by samreid** [comment]
Ready for testing in this version: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.85/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
👍
