### ISSUE TITLE
Carousel freezes up

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#87]
See https://github.com/phetsims/circuit-construction-kit-dc/issues/80

Sometimes the carousel locks up.  @arouinfar and @phet-steele and @samreid haven't reproduced the problem yet, but it came up several times during interviews.

**Comment by samreid** [comment]
@arouinfar or @phet-steele if you see this problem again, a stack trace (from the console) may come in handy.

**Comment by samreid** [comment]
@arouinfar shared a video clip that demonstrated the problem.  Notably:

> The carousel dots remained responsive, but the page up/down arrows and the items were frozen.

The rest of the sim remained responsive too.

**Comment by arouinfar** [comment]
@samreid I just edited the clip to include more of what happened after the browser refresh. After dragging 3 batteries into the play space and adjusting their positions, the carousel froze again.

**Comment by samreid** [comment]
I can see the problem after the browser refresh, but am still having trouble replicating the problem.  Hopefully a stack trace will contain valuable information (but maybe not).

**Comment by samreid** [comment]
@phet-steele discovered that double clicking a vertex causes this problem.  Nice work @phet-steele!  @jonathanolson and I will pursue a strategy for listening to the scenery event channel for a way to address this issue.

**Comment by arouinfar** [comment]
Way to go @phet-steele!!

**Comment by samreid** [comment]
Fixed by @jonathanolson in the preceding commits, closing.
