### ISSUE TITLE
Consider tilted/rotatable voltage meter probes

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/circuit-construction-kit-dc#88]
@arouinfar when playing around with the latest version of CCK (and making a gif or two to tweet out), I noticed that having the voltage meter probes be straight vertical was a bit awkward. I think there is a tendency to build circuit in a "grid-like" manner, so components are either generally vertical or horizontal. The current orientation of the probes works reasonable for horizontal components but is fairly awkward with vertical components (as they cover much of the component).

I think we should tilt the probes as in the java version (I think the meter in the toolbox could still have them vertical for space concerns, but tilted once pulled out)

![vm](https://user-images.githubusercontent.com/4051174/28386931-6e0b1780-6c8a-11e7-88c0-0f39212eb07b.PNG)

At some point, we could also consider if being able to rotate the probe would be nice UX. I am guessing that the tilt will alleviate most of my concerns.

**Comment by samreid** [comment]
> I think we should tilt the probes as in the java version (I think the meter in the toolbox could still have them vertical for space concerns, but tilted once pulled out)

It will most likely be simpler in the code to rotate the probes in the toolbox and I think it would look nice to be consistent, but I'll have to see how much more horizontal space it takes up.

**Comment by arouinfar** [comment]
@samreid I'd be fine with tilted probes in the toolbox, so long as there's enough room to accommodate them.

**Comment by samreid** [comment]
Rotated probes are available in dev.86.  @ariel-phet and @arouinfar can you please test it out?

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.86/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
I like it @samreid!

**Comment by ariel-phet** [comment]
Looks good. Closing
