### ISSUE TITLE
Voltmeter Readout for Grab Bag reading '?' instead of '0.00 V'

### ISSUE THREAD

**Issue by Denz1994** [phetsims/circuit-construction-kit-dc#89]
Probing the vertices of isolated non-wire components gives a readout of '0.00 V'. Consider the image below.
![image](https://user-images.githubusercontent.com/13894380/28386713-a93d3d02-6c89-11e7-81e6-83f0f9dfe7c0.png)

Additionally, probing the body (not the vertices) of the non-wire component gives a readout of '?'.
Consider the image below.
![image](https://user-images.githubusercontent.com/13894380/28386881-3b179934-6c8a-11e7-81b2-346fb0abf2e6.png)

1. Is this behavior intentional?
- I assume this was done because the body of the components is highly insulated.

2. Should grab bag items have the same behavior?

- There is no difference physically between the vertex of a paperclip and the body of a paper clip. Therefore we shouldn't treat the read out any differently. I would exclude the pencil from this because the lead is insulated by wood.

I understand this is minor, but the difference in behavior between the vertices and body of non-grab bag components speaks to the composition of its real life counterpart. 

Thoughts @arouinfar and @samreid ?

**Comment by arouinfar** [comment]
Great observation @Denz1994. I believe the behavior was intentional, as the body of most objects is insulated. However, I would agree that the grab bag items with a metallic body (paperclip and coin) should behave like a wire.

**Comment by arouinfar** [comment]
@samreid would this be akin to #63?

**Comment by Denz1994** [comment]
>  However, I would agree that the grab bag items with a metallic body (paper clip and coin) should behave like a wire.

Adding on to that, the dollar, dog, hand, and eraser should have a voltage readout of '?' as the whole component is an insulator compared to the vertices.

**Comment by samreid** [comment]
So it seems we will need to add a new property of resistors that indicates whether it is metallic or shielded, with paperclip and coin being the only metallic ones at the moment.

**Comment by samreid** [comment]
Consensus: use a region like the wire touch area for determining whether contains sensor point for resistors, for 1.0 but not for AAPT

**Comment by samreid** [comment]
Now that #93 is resolved, I think we no longer need to implement the preceding suggestion since the mouse areas are pretty similar to the wire touch area. But we still need to do https://github.com/phetsims/circuit-construction-kit-dc/issues/89#issuecomment-316576235

**Comment by samreid** [comment]
I added an `isMetallic` property for resistors and use it to check voltmeter readings. I posted a version here for testing:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.92/circuit-construction-kit-dc_en.html

@arouinfar can you please take a look?  Also be aware of the preceding comment that describes that fixing #93 (hopefully) made it so we don't need another custom hit region.

**Comment by arouinfar** [comment]
Love it!
