### ISSUE TITLE
Control panels should all have the same width

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-dc#9]
For https://github.com/phetsims/tasks/issues/765.

I know this is totally a nit-picky, pixel-polishing request, but can the "Show Electrons" panel have the same width as the toolbox below it? It seems like a quick tweak, and I think it will make the sim look cleaner.

**Comment by samreid** [comment]
This seems like a good opportunity for me to test out AlignGroup, see the sun demo.

**Comment by samreid** [comment]
@arouinfar what should happen for languages where the show electrons panel is much wider than the sensor toolbox?

**Comment by arouinfar** [comment]
@samreid generally we have a limit to how wide we allow panels to expand for i18n -- I think 50 px has worked well in the past. Would it be possible to keep all panels the same width? Say the "Show Current" panel needs to expand by 40 px, but "Wire Resistivity" only needs 30 px to accommodate the translated string. In this situation, could you add some logic that would expand all panels by 40 px (including the toolbox)? I think it will keep the look a bit cleaner.

**Comment by samreid** [comment]
I will likely need to add the ammeter to the sensor toolbox before I can complete this, because it may put a lower bound on the control panel widths.

**Comment by samreid** [comment]
After I started mocking up the sensor toolbox, the layout is looking like this:

![image](https://cloud.githubusercontent.com/assets/679486/26213384/0af1d1c0-3bb6-11e7-92b1-b86e53e85b90.png)

Not sure how to adjust the size of the upper panel to match this.  Seems like I would have to add a lot of blank space--should that be on the right margin?   @arouinfar can you take a look?

**Comment by arouinfar** [comment]
@samreid I think adding extra space to the right side Show Current panel will look fine, especially once the icons for electron and conventional current are added to the panel. I don't think the scene selection buttons need to match the width of the panels. Their current size and spacing looks good. I would center them below the panels.

![image](https://cloud.githubusercontent.com/assets/8419308/26217287/0baf224e-3bc4-11e7-9790-4faf8eaac78a.png)

**Comment by arouinfar** [comment]
By the way @samreid, I also made the toolbox icons a bit smaller to make room for the inline ammeter, which made the panel a bit narrower than it used to be. The screenshot you provided in https://github.com/phetsims/circuit-construction-kit-dc/issues/9#issuecomment-302465535 looks like you already may have narrowed the panel, but I just wanted to let you know.

**Comment by samreid** [comment]
@arouinfar can you review http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.22/circuit-construction-kit-dc_en.html and comment on the panel sizes in screen 3?  I'd like to know if you like the size of the display options panel and its fonts and want to match things around that, or if you want to shrink that font + margins at all.

**Comment by arouinfar** [comment]
@samreid I've reviewed the panels in dev.48, and have a few suggestions:

Show Current Panel
- [ ] Reduce font size to match "Wire Resistivity" 


Wire Resistivity & Battery Resistance Panels
- [ ] Widen panels to match Show Current panel width
- [ ] Lengthen slider tracks in proportion to the wider panels
- [ ] Increase top padding on -/+ button to match left padding (panel title will also need to move down to remain center-aligned with the button)
- [ ] Reduce slider thumb by ~25%  (this should free up enough vertical space for the previous item)

**Comment by samreid** [comment]
> Reduce font size to match "Wire Resistivity"

When @Denz1994 and I tried this, it did not end up reducing the size of that panel.

Original:
![image](https://user-images.githubusercontent.com/679486/26953556-482f11a2-4c68-11e7-9189-18b2b9edf9df.png)

With smaller font:
![image](https://user-images.githubusercontent.com/679486/26953562-503d5c14-4c68-11e7-9539-ce77f7785d13.png)

@Denz1994 and I suspect the reason is that the checkboxes and spacing are still the same large size.  We will try reducing them.

**Comment by samreid** [comment]
We adjusted the radio button and checkbox sizes and now its more like this:

![image](https://user-images.githubusercontent.com/679486/26953642-e6df96dc-4c68-11e7-8330-cfb978cca931.png)

**Comment by samreid** [comment]
> Keep consistent width across all screens

@Denz1994 and I thought of a way we could implement this (by sharing an AlignGroup across the screens) but are hesitant to implement it because it would introduce a lot of blank space on screens 1-2.  @arouinfar thoughts?

**Comment by samreid** [comment]
> Lengthen slider tracks in proportion to the wider panels

We do not have a way to do this dynamically but we will choose a good default size that works well for English, and make sure other languages don't get too wide.

**Comment by samreid** [comment]
@Denz1994 and I made numerous changes in this issue.  Some questions or caveats appear in the preceding comments.  We published a dev version here:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.57/circuit-construction-kit-dc_en.html

@arouinfar can you please take a look and provide feedback?

**Comment by arouinfar** [comment]
@samreid the Lab screen looks great!! I've noticed that the Show Current panel and sensor toolbox are slightly narrower on the Intro and Explore screens. Can they be widened to match the Lab screen?

**Comment by samreid** [comment]
Proposed fix is in dev.64, please test:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.64/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Looks great @samreid. Thanks!
