### ISSUE TITLE
Clicking near a tweaker button shouldn't dismiss it

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#90]

**Comment by samreid** [comment]
I added a touch/mouse area around the bottom controls--clicking in that area will not dismiss the controls:

![image](https://user-images.githubusercontent.com/679486/28491638-f2e2904a-6eb1-11e7-992b-534e82728feb.png)

**Comment by samreid** [comment]
Fix committed, @arouinfar could you please test this out and look for related issues?

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.94/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
👍
