### ISSUE TITLE
Schematic pointer areas are buggy

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#93]
![image](https://user-images.githubusercontent.com/679486/28439516-7f39d354-6d5f-11e7-8ca7-e32035cc770b.png)

**Comment by samreid** [comment]
Heads up!  Those are mouse areas too!

**Comment by samreid** [comment]
Fixed for resistors, and that will go a long way to fixing https://github.com/phetsims/circuit-construction-kit-dc/issues/89 as well.

![image](https://user-images.githubusercontent.com/679486/28440809-221c4160-6d65-11e7-9148-75c5f8294152.png)

**Comment by samreid** [comment]
Proposed fix is in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html

**Comment by arouinfar** [comment]
Looks good to me @samreid.
