### ISSUE TITLE
Wire stub visibility is shared between screens

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#94]
1. Drag out one wire on each screen
2. On one of the screens, enable schematic view
3. Switch to the other screen, the wire there will be missing its stubs. Move the wire around to fix.
![image](https://user-images.githubusercontent.com/5863899/28443937-9c9ca194-6d76-11e7-89fb-368a6ae27af3.png)

4. Switch back to the screen using schematic view, the wire will HAVE stubs (assuming you fixed step 3). Move the wire around to fix.
![image](https://user-images.githubusercontent.com/5863899/28443947-affceda2-6d76-11e7-8d5d-6008b005c532.png)

Assigning to people to delegate for AAPT. Verified on http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html with Win 10 Chrome. For phetsims/QA/issues/26.

**Comment by ariel-phet** [comment]
This does not need to be fixed for AAPT

**Comment by samreid** [comment]
Proposed fix is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.95/circuit-construction-kit-dc_en.html

@phet-steele can you please test?

**Comment by phet-steele** [comment]
Fixed, thanks!
