### ISSUE TITLE
Conventional current arrow direction is dependent on a lightbulb's angle

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#95]
Lightbulbs that are upside-down or sideways, and everything in between, have the conventional current arrows pointing in the completing wrong way.

The top bulb (upside-down) has the arrows pointing the opposite direction as the arrows in the wires it is connected to (the wires are correct).

![image](https://user-images.githubusercontent.com/5863899/28444459-966af966-6d7a-11e7-9b5d-13e4fe4c175c.png)

Seen in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html on Win 10 Chrome. For phetsims/QA/issues/26.

**Comment by ariel-phet** [comment]
I think Kathy can be told to only use right side up bulbs. NOT for AAPT.

However, a higher priority bug to fix in general. 

Leaving @arouinfar assigned to note this as one of the "known" issues

**Comment by samreid** [comment]
Proposed fix is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.96/circuit-construction-kit-dc_en.html

@phet-steele can you please take a look?

**Comment by phet-steele** [comment]
Fixed, thanks!
