### ISSUE TITLE
Animation Speed text remains after Reset All

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#97]
Found by @arouinfar.

1. Create a short.
2. Reset All, text remains along the bottom of the screen.

Fixes upon further interaction with the sim.

Seen in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html on Win 10 Chrome. For phetsims/QA#26.

**Comment by samreid** [comment]
Proposed fix is here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.91/circuit-construction-kit-dc_en.html

@phet-steele can you please take a look?

**Comment by phet-steele** [comment]
Fixed.
