### ISSUE TITLE
Resistor color bands stop changing after 100

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#98]
Discovered in https://github.com/phetsims/circuit-construction-kit-dc/issues/73 when increasing the resistor resistance the color bands change every ohm, but above 100 they only change at 105, and 115.  @arouinfar do we need to go to 4 bands?  If so, is it only 4-band after 100?  Alternatively, are these values within tolerance?  Or should we change the tolerance band so that these bad values are within error?

**Comment by arouinfar** [comment]
Thanks for asking @samreid. I double checked the 100-120 ohms range, and the value is always within the tolerance range of the displayed colors. I'd say we're fine to leave things as they are.
